/*
* Copyright (c) File ,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:CanCfg.c
* Description: CAN Mailboxes and messages configurations file, this is auto-generated by CCAG tool which is developed by HSNE and should never be modified manually
* REQ IDs: 
* History:
* Time:2020/5/7 11:33:53
* User:lixiangping
*/

/* ---- Source switch on ------------------------------------------------------*/

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "canCfg.h"
#include "hs_types.h"
#include "canCfg_signals.h"
#include "canCfg_import.h"


/*-----------------------------------------------------------------------------
                   		Module local defines and constants
------------------------------------------------------------------------------*/
#define m_C_CAN_MsgCnt 35
#define m_PT_CAN_MsgCnt 63
#define m_RESERVED_CAN_MsgCnt 3
#define m_canMod_cnt 3


/*------------------------------------------------------------------------------
                                 Module local types
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
                                Local data at RAM
------------------------------------------------------------------------------*/
static canMsgScheData_t CLASS_CANMsgScheData[m_C_CAN_MsgCnt] =
{
    {FALSE,2,0},
    {FALSE,1,0},
    {FALSE,0,0},
	{FALSE,2,0},
	{FALSE,1,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},

	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},

	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},

	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0}
};


static canMsgSortInfo_t CLASS_CANMsgSortOrder[m_C_CAN_MsgCnt] =
{
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0}
};

static canMsgScheData_t RESERVED_CANMsgScheData[m_RESERVED_CAN_MsgCnt] =
{
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0}
};


static canMsgSortInfo_t RESERVED_CANMsgSortOrder[m_RESERVED_CAN_MsgCnt] = 
{
    {0,0,0},
    {0,0,0},
    {0,0,0}
};

static canMsgScheData_t PT_CANMsgScheData[m_PT_CAN_MsgCnt] =
{
    {FALSE,0,0},
    {FALSE,1,0},
    {FALSE,0,0},
    {FALSE,1,0},
    {FALSE,2,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,7,0},
    {FALSE,1,0},

    {FALSE,3,0},
    {FALSE,7,0},
    {FALSE,4,0},
    {FALSE,6,0},
    {FALSE,11,0},
    {FALSE,5,0},
    {FALSE,17,0},
    {FALSE,11,0},
    {FALSE,6,0},
    {FALSE,3,0},

    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},

    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},

    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},
    {FALSE,0,0},


    {FALSE,0,0},
	{FALSE,0,0},
	{FALSE,0,0}
};


static canMsgSortInfo_t PT_CANMsgSortOrder[m_PT_CAN_MsgCnt] = 
{
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},


    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},
    {0,0,0},

    {0,0,0},
	{0,0,0},
	{0,0,0}
};



/*------------------------------------------------------------------------------
                                Global data at RAM
------------------------------------------------------------------------------*/
hs_u1_t RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txReady = FALSE;
hs_BOOL RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txFail = FALSE;
hs_BOOL RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxOverLap = TRUE;
hs_u1_t RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxTimeout = FALSE;
hs_BOOL RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_received = FALSE;
hs_u1_t RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txReady = FALSE;
hs_BOOL RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txFail = FALSE;


hs_u1_t CCP_CAN_0x201_VCU_frontMotorTorque_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x201_VCU_frontMotorTorque_txReady = FALSE;
hs_BOOL CCP_CAN_0x201_VCU_frontMotorTorque_txFail = FALSE;
hs_u1_t CCP_CAN_0x211_VCU_rearMotorTorque_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x211_VCU_rearMotorTorque_txReady = FALSE;
hs_BOOL CCP_CAN_0x211_VCU_rearMotorTorque_txFail = FALSE;
hs_u1_t CCP_CAN_0x3A1_VCU_stateCha1_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x3A1_VCU_stateCha1_txReady = FALSE;
hs_BOOL CCP_CAN_0x3A1_VCU_stateCha1_txFail = FALSE;
hs_u1_t CCP_CAN_0x241_VCU_stateCha2_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x241_VCU_stateCha2_txReady = FALSE;
hs_BOOL CCP_CAN_0x241_VCU_stateCha2_txFail = FALSE;
hs_u1_t CCP_CAN_0x3B1_VCU_stateCha3_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x3B1_VCU_stateCha3_txReady = FALSE;
hs_BOOL CCP_CAN_0x3B1_VCU_stateCha3_txFail = FALSE;
hs_u1_t CCP_CAN_0x101_VCU_vehicleTorque_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x101_VCU_vehicleTorque_txReady = FALSE;
hs_BOOL CCP_CAN_0x101_VCU_vehicleTorque_txFail = FALSE;
hs_BOOL CCP_CAN_0x232_ESC_torqueReq_front_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x232_ESC_torqueReq_front_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x232_ESC_torqueReq_front_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x232_ESC_torqueReq_front_received = FALSE;
hs_BOOL CCP_CAN_0x222_ESC_torqueReq_rear_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x222_ESC_torqueReq_rear_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x222_ESC_torqueReq_rear_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x222_ESC_torqueReq_rear_received = FALSE;
hs_BOOL CCP_CAN_0x58_TBOX_remoteCmd_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x58_TBOX_remoteCmd_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x58_TBOX_remoteCmd_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x58_TBOX_remoteCmd_received = FALSE;
hs_BOOL CCP_CAN_0x3FE_IVI_timeAndGPS_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x3FE_IVI_timeAndGPS_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x3FE_IVI_timeAndGPS_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x3FE_IVI_timeAndGPS_received = FALSE;
hs_BOOL CCP_CAN_0x4FE_DiagPhysReqToBMS_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x4FE_DiagPhysReqToBMS_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x4FE_DiagPhysReqToBMS_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x4FE_DiagPhysReqToBMS_received = FALSE;
hs_BOOL CCP_CAN_0xA5_IVI_pwrSet_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0xA5_IVI_pwrSet_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0xA5_IVI_pwrSet_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0xA5_IVI_pwrSet_received = FALSE;
hs_BOOL CCP_CAN_0x122_ESC_wheelSpd_Rear_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x122_ESC_wheelSpd_Rear_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x122_ESC_wheelSpd_Rear_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x122_ESC_wheelSpd_Rear_received = FALSE;
hs_BOOL CCP_CAN_0x124_EPS_state_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x124_EPS_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x124_EPS_state_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x124_EPS_state_received = FALSE;
hs_BOOL CCP_CAN_0x142_ESC_wheelSpd_Front_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x142_ESC_wheelSpd_Front_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x142_ESC_wheelSpd_Front_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x142_ESC_wheelSpd_Front_received = FALSE;
hs_BOOL CCP_CAN_0x144_EPS_SAS_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x144_EPS_SAS_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x144_EPS_SAS_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x144_EPS_SAS_received = FALSE;
hs_BOOL CCP_CAN_0x1BE_IVI_chassisSet_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x1BE_IVI_chassisSet_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x1BE_IVI_chassisSet_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x1BE_IVI_chassisSet_received = FALSE;
hs_BOOL CCP_CAN_0x1C5_iB_esc1_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x1C5_iB_esc1_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x1C5_iB_esc1_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x1C5_iB_esc1_received = FALSE;
hs_BOOL CCP_CAN_0x1D5_GW_icm_ivi_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x1D5_GW_icm_ivi_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x1D5_GW_icm_ivi_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x1D5_GW_icm_ivi_received = FALSE;
hs_BOOL CCP_CAN_0x212_ESC_state1_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x212_ESC_state1_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x212_ESC_state1_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x212_ESC_state1_received = FALSE;
hs_BOOL CCP_CAN_0x219_MRR_acc_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x219_MRR_acc_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x219_MRR_acc_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x219_MRR_acc_received = FALSE;
hs_BOOL CCP_CAN_0x21A_MPC_state_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x21A_MPC_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x21A_MPC_state_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x21A_MPC_state_received = FALSE;
hs_BOOL CCP_CAN_0x242_ESC_apaSet_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x242_ESC_apaSet_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x242_ESC_apaSet_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x242_ESC_apaSet_received = FALSE;
hs_BOOL CCP_CAN_0x252_ESC_yawState_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x252_ESC_yawState_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x252_ESC_yawState_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x252_ESC_yawState_received = FALSE;
hs_BOOL CCP_CAN_0x272_ESC_wssFront_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x272_ESC_wssFront_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x272_ESC_wssFront_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x272_ESC_wssFront_received = FALSE;
hs_BOOL CCP_CAN_0x282_ESC_wssRear_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x282_ESC_wssRear_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x282_ESC_wssRear_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x282_ESC_wssRear_received = FALSE;
hs_BOOL CCP_CAN_0x2A1_TSV31_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2A1_TSV31_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2A1_TSV31_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2A1_TSV31_received = FALSE;
hs_BOOL CCP_CAN_0x2A2_ESC_state2_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2A2_ESC_state2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2A2_ESC_state2_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2A2_ESC_state2_received = FALSE;
hs_BOOL CCP_CAN_0x2A5_iB_esc2_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2A5_iB_esc2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2A5_iB_esc2_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2A5_iB_esc2_received = FALSE;
hs_BOOL CCP_CAN_0x2C2_ESC_epb_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2C2_ESC_epb_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2C2_ESC_epb_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2C2_ESC_epb_received = FALSE;
hs_BOOL CCP_CAN_0x2CE_BCM_peps_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2CE_BCM_peps_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2CE_BCM_peps_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2CE_BCM_peps_received = FALSE;
hs_BOOL CCP_CAN_0x2FE_IC_state_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x2FE_IC_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x2FE_IC_state_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x2FE_IC_state_received = FALSE;
hs_BOOL CCP_CAN_0x319_SWM_Set_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x319_SWM_Set_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x319_SWM_Set_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x319_SWM_Set_received = FALSE;
hs_BOOL CCP_CAN_0x341_ASC_state1_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x341_ASC_state1_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x341_ASC_state1_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x341_ASC_state1_received = FALSE;
hs_BOOL CCP_CAN_0x380_ACU_state_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x380_ACU_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x380_ACU_state_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x380_ACU_state_received = FALSE;
hs_BOOL CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x39E_GW_AC_BCM_CHACAN_received = FALSE;
hs_u1_t CAN_3_0x301_VCU_pwr_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x301_VCU_pwr_txReady = FALSE;
hs_BOOL CAN_3_0x301_VCU_pwr_txFail = FALSE;
hs_BOOL CAN_3_0x302_MCUR0_temperature_rxOverLap = TRUE;
hs_u1_t CAN_3_0x302_MCUR0_temperature_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x302_MCUR0_temperature_rxTimeout = FALSE;
hs_BOOL CAN_3_0x302_MCUR0_temperature_received = FALSE;
hs_BOOL CAN_3_0x303_MCUF0_temperature_rxOverLap = TRUE;
hs_u1_t CAN_3_0x303_MCUF0_temperature_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x303_MCUF0_temperature_rxTimeout = FALSE;
hs_BOOL CAN_3_0x303_MCUF0_temperature_received = FALSE;
hs_BOOL CAN_3_0x304_BMS_temperature_rxOverLap = TRUE;
hs_u1_t CAN_3_0x304_BMS_temperature_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x304_BMS_temperature_rxTimeout = FALSE;
hs_BOOL CAN_3_0x304_BMS_temperature_received = FALSE;
hs_u1_t CAN_3_0x5A4_VCU_DutyCycle_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x5A4_VCU_DutyCycle_txReady = FALSE;
hs_BOOL CAN_3_0x5A4_VCU_DutyCycle_txFail = FALSE;
hs_u1_t CAN_3_0x1B1_VCU_GCUCtlLmt_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x1B1_VCU_GCUCtlLmt_txReady = FALSE;
hs_BOOL CAN_3_0x1B1_VCU_GCUCtlLmt_txFail = FALSE;
hs_u1_t CAN_3_0x2FA_VCU_Indication_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x2FA_VCU_Indication_txReady = FALSE;
hs_BOOL CAN_3_0x2FA_VCU_Indication_txFail = FALSE;
hs_u1_t CAN_3_0x5A5_VCU_PTCPower_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x5A5_VCU_PTCPower_txReady = FALSE;
hs_BOOL CAN_3_0x5A5_VCU_PTCPower_txFail = FALSE;
hs_u1_t CAN_3_0x331_VCU_Rev_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x331_VCU_Rev_txReady = FALSE;
hs_BOOL CAN_3_0x331_VCU_Rev_txFail = FALSE;
hs_u1_t CAN_3_0x32E_VCU_RevV2VPower_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x32E_VCU_RevV2VPower_txReady = FALSE;
hs_BOOL CAN_3_0x32E_VCU_RevV2VPower_txFail = FALSE;
hs_u1_t CAN_3_0x321_VCU_alertMatrix0_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x321_VCU_alertMatrix0_txReady = FALSE;
hs_BOOL CAN_3_0x321_VCU_alertMatrix0_txFail = FALSE;
hs_u1_t CAN_3_0x561_VCU_range_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x561_VCU_range_txReady = FALSE;
hs_BOOL CAN_3_0x561_VCU_range_txFail = FALSE;
hs_u1_t CAN_3_0x551_VCU_standard_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x551_VCU_standard_txReady = FALSE;
hs_BOOL CAN_3_0x551_VCU_standard_txFail = FALSE;
hs_u1_t CAN_3_0x111_VCU_state_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x111_VCU_state_txReady = FALSE;
hs_BOOL CAN_3_0x111_VCU_state_txFail = FALSE;
hs_u1_t CAN_3_0x401_VCU_subPower_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x401_VCU_subPower_txReady = FALSE;
hs_BOOL CAN_3_0x401_VCU_subPower_txFail = FALSE;
hs_u1_t CAN_3_0x511_VCU_tboxGeneralAlert_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x511_VCU_tboxGeneralAlert_txReady = FALSE;
hs_BOOL CAN_3_0x511_VCU_tboxGeneralAlert_txFail = FALSE;
hs_u1_t CAN_3_0x521_VCU_thermal_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x521_VCU_thermal_txReady = FALSE;
hs_BOOL CAN_3_0x521_VCU_thermal_txFail = FALSE;
hs_u1_t CAN_3_0x531_VCU_thermal2_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x531_VCU_thermal2_txReady = FALSE;
hs_BOOL CAN_3_0x531_VCU_thermal2_txFail = FALSE;
hs_u1_t CAN_3_0x5F1_VCU_version_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x5F1_VCU_version_txReady = FALSE;
hs_BOOL CAN_3_0x5F1_VCU_version_txFail = FALSE;
hs_u1_t CAN_3_0x101_VCU_torque_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x101_VCU_torque_txReady = FALSE;
hs_BOOL CAN_3_0x101_VCU_torque_txFail = FALSE;
hs_u1_t CAN_3_0x441_VCU_vehicle_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x441_VCU_vehicle_txReady = FALSE;
hs_BOOL CAN_3_0x441_VCU_vehicle_txFail = FALSE;
hs_BOOL CAN_3_0x3A6_AC_pwtAlloted_rxOverLap = TRUE;
hs_u1_t CAN_3_0x3A6_AC_pwtAlloted_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x3A6_AC_pwtAlloted_rxTimeout = FALSE;
hs_BOOL CAN_3_0x3A6_AC_pwtAlloted_received = FALSE;
hs_BOOL CAN_3_0x731_Diag_PhyReq_VCU_rxOverLap = TRUE;
hs_u1_t CAN_3_0x731_Diag_PhyReq_VCU_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x731_Diag_PhyReq_VCU_rxTimeout = FALSE;
hs_BOOL CAN_3_0x731_Diag_PhyReq_VCU_received = FALSE;
hs_BOOL CAN_3_0x7E7_OBD_PhyReq_VCU_rxOverLap = TRUE;
hs_u1_t CAN_3_0x7E7_OBD_PhyReq_VCU_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x7E7_OBD_PhyReq_VCU_rxTimeout = FALSE;
hs_BOOL CAN_3_0x7E7_OBD_PhyReq_VCU_received = FALSE;
hs_BOOL CAN_3_0x7DF_Diag_FuncReq_rxOverLap = TRUE;
hs_u1_t CAN_3_0x7DF_Diag_FuncReq_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x7DF_Diag_FuncReq_rxTimeout = FALSE;
hs_BOOL CAN_3_0x7DF_Diag_FuncReq_received = FALSE;
hs_u1_t CAN_3_0x79A_CCP_Tx_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x79A_CCP_Tx_txReady = FALSE;
hs_BOOL CAN_3_0x79A_CCP_Tx_txFail = FALSE;
hs_BOOL CAN_3_0x797_CCP_Rx_rxOverLap = TRUE;
hs_u1_t CAN_3_0x797_CCP_Rx_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x797_CCP_Rx_rxTimeout = FALSE;
hs_BOOL CAN_3_0x797_CCP_Rx_received = FALSE;
hs_u1_t CAN_3_0x7B1_Diag_Resp_VCU_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x7B1_Diag_Resp_VCU_txReady = FALSE;
hs_BOOL CAN_3_0x7B1_Diag_Resp_VCU_txFail = FALSE;
hs_u1_t CAN_3_0x7EF_OBD_Resp_VCU_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x7EF_OBD_Resp_VCU_txReady = FALSE;
hs_BOOL CAN_3_0x7EF_OBD_Resp_VCU_txFail = FALSE;
hs_BOOL CAN_3_0x3F3_IC_info_rxOverLap = TRUE;
hs_u1_t CAN_3_0x3F3_IC_info_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x3F3_IC_info_rxTimeout = FALSE;
hs_BOOL CAN_3_0x3F3_IC_info_received = FALSE;
hs_BOOL CAN_3_0x492_IC_state2_rxOverLap = TRUE;
hs_u1_t CAN_3_0x492_IC_state2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x492_IC_state2_rxTimeout = FALSE;
hs_BOOL CAN_3_0x492_IC_state2_received = FALSE;
hs_BOOL CAN_3_0x394_POT_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x394_POT_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x394_POT_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x394_POT_state_received = FALSE;
hs_BOOL CAN_3_0x407_OBC_state1_rxOverLap = TRUE;
hs_u1_t CAN_3_0x407_OBC_state1_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x407_OBC_state1_rxTimeout = FALSE;
hs_BOOL CAN_3_0x407_OBC_state1_received = FALSE;
hs_BOOL CAN_3_0x487_OBC_state2_rxOverLap = TRUE;
hs_u1_t CAN_3_0x487_OBC_state2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x487_OBC_state2_rxTimeout = FALSE;
hs_BOOL CAN_3_0x487_OBC_state2_received = FALSE;
hs_BOOL CAN_3_0x75_IVI_control_rxOverLap = TRUE;
hs_u1_t CAN_3_0x75_IVI_control_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x75_IVI_control_rxTimeout = FALSE;
hs_BOOL CAN_3_0x75_IVI_control_received = FALSE;
hs_BOOL CAN_3_0x7E_TBOX_chargeSet_rxOverLap = TRUE;
hs_u1_t CAN_3_0x7E_TBOX_chargeSet_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x7E_TBOX_chargeSet_rxTimeout = FALSE;
hs_BOOL CAN_3_0x7E_TBOX_chargeSet_received = FALSE;
hs_BOOL CAN_3_0x4FE_TBOX_VehicleMode_rxOverLap = TRUE;
hs_u1_t CAN_3_0x4FE_TBOX_VehicleMode_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x4FE_TBOX_VehicleMode_rxTimeout = FALSE;
hs_BOOL CAN_3_0x4FE_TBOX_VehicleMode_received = FALSE;
hs_BOOL CAN_3_0x514_BMS_metric_rxOverLap = TRUE;
hs_u1_t CAN_3_0x514_BMS_metric_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x514_BMS_metric_rxTimeout = FALSE;
hs_BOOL CAN_3_0x514_BMS_metric_received = FALSE;
hs_BOOL CAN_3_0x574_BMS_tboxRequest_rxOverLap = TRUE;
hs_u1_t CAN_3_0x574_BMS_tboxRequest_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x574_BMS_tboxRequest_rxTimeout = FALSE;
hs_BOOL CAN_3_0x574_BMS_tboxRequest_received = FALSE;
hs_u1_t CAN_3_0x631_NM_VCU_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x631_NM_VCU_txReady = FALSE;
hs_BOOL CAN_3_0x631_NM_VCU_txFail = FALSE;
hs_BOOL CAN_3_0x632_NM_MCUR0_rxOverLap = TRUE;
hs_u1_t CAN_3_0x632_NM_MCUR0_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x632_NM_MCUR0_rxTimeout = FALSE;
hs_BOOL CAN_3_0x632_NM_MCUR0_received = FALSE;
hs_BOOL CAN_3_0x634_NM_BMS_rxOverLap = TRUE;
hs_u1_t CAN_3_0x634_NM_BMS_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x634_NM_BMS_rxTimeout = FALSE;
hs_BOOL CAN_3_0x634_NM_BMS_received = FALSE;
hs_BOOL CAN_3_0x637_NM_OBCM_rxOverLap = TRUE;
hs_u1_t CAN_3_0x637_NM_OBCM_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x637_NM_OBCM_rxTimeout = FALSE;
hs_BOOL CAN_3_0x637_NM_OBCM_received = FALSE;
hs_BOOL CAN_3_0x63E_NM_GW_PT_rxOverLap = TRUE;
hs_u1_t CAN_3_0x63E_NM_GW_PT_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x63E_NM_GW_PT_rxTimeout = FALSE;
hs_BOOL CAN_3_0x63E_NM_GW_PT_received = FALSE;
hs_BOOL CAN_3_0x102_MCUR0_torque_rxOverLap = TRUE;
hs_u1_t CAN_3_0x102_MCUR0_torque_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x102_MCUR0_torque_rxTimeout = FALSE;
hs_BOOL CAN_3_0x102_MCUR0_torque_received = FALSE;
hs_BOOL CAN_3_0x103_MCUF0_torque_rxOverLap = TRUE;
hs_u1_t CAN_3_0x103_MCUF0_torque_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x103_MCUF0_torque_rxTimeout = FALSE;
hs_BOOL CAN_3_0x103_MCUF0_torque_received = FALSE;
hs_BOOL CAN_3_0x104_BMS_meas_rxOverLap = TRUE;
hs_u1_t CAN_3_0x104_BMS_meas_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x104_BMS_meas_rxTimeout = FALSE;
hs_BOOL CAN_3_0x104_BMS_meas_received = FALSE;
hs_BOOL CAN_3_0x112_MCUR0_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x112_MCUR0_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x112_MCUR0_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x112_MCUR0_state_received = FALSE;
hs_BOOL CAN_3_0x113_MCUF0_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x113_MCUF0_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x113_MCUF0_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x113_MCUF0_state_received = FALSE;
hs_BOOL CAN_3_0x114_BMS_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x114_BMS_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x114_BMS_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x114_BMS_state_received = FALSE;
hs_BOOL CAN_3_0x126_BMS_RevFaultInfo_rxOverLap = TRUE;
hs_u1_t CAN_3_0x126_BMS_RevFaultInfo_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x126_BMS_RevFaultInfo_rxTimeout = FALSE;
hs_BOOL CAN_3_0x126_BMS_RevFaultInfo_received = FALSE;
hs_BOOL CAN_3_0x134_BMS_driveLimits_rxOverLap = TRUE;
hs_u1_t CAN_3_0x134_BMS_driveLimits_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x134_BMS_driveLimits_rxTimeout = FALSE;
hs_BOOL CAN_3_0x134_BMS_driveLimits_received = FALSE;
hs_BOOL CAN_3_0x2C1_BCM_peps_rxOverLap = TRUE;
hs_u1_t CAN_3_0x2C1_BCM_peps_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x2C1_BCM_peps_rxTimeout = FALSE;
hs_BOOL CAN_3_0x2C1_BCM_peps_received = FALSE;
hs_BOOL CAN_3_0x309_GSM_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x309_GSM_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x309_GSM_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x309_GSM_state_received = FALSE;
hs_BOOL CAN_3_0x312_MCUR0_state2_rxOverLap = TRUE;
hs_u1_t CAN_3_0x312_MCUR0_state2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x312_MCUR0_state2_rxTimeout = FALSE;
hs_BOOL CAN_3_0x312_MCUR0_state2_received = FALSE;
hs_BOOL CAN_3_0x313_MCUF0_state2_rxOverLap = TRUE;
hs_u1_t CAN_3_0x313_MCUF0_state2_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x313_MCUF0_state2_rxTimeout = FALSE;
hs_BOOL CAN_3_0x313_MCUF0_state2_received = FALSE;
hs_BOOL CAN_3_0x354_BMS_Rev_rxOverLap = TRUE;
hs_u1_t CAN_3_0x354_BMS_Rev_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x354_BMS_Rev_rxTimeout = FALSE;
hs_BOOL CAN_3_0x354_BMS_Rev_received = FALSE;
hs_BOOL CAN_3_0x387_OBC_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x387_OBC_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x387_OBC_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x387_OBC_state_received = FALSE;
hs_BOOL CAN_3_0x38D_DCDC_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x38D_DCDC_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x38D_DCDC_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x38D_DCDC_state_received = FALSE;
hs_BOOL CAN_3_0x38E_ACU_state_rxOverLap = TRUE;
hs_u1_t CAN_3_0x38E_ACU_state_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x38E_ACU_state_rxTimeout = FALSE;
hs_BOOL CAN_3_0x38E_ACU_state_received = FALSE;
hs_BOOL CAN_3_0x39E_AC_temp_pressure_rxOverLap = TRUE;
hs_u1_t CAN_3_0x39E_AC_temp_pressure_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x39E_AC_temp_pressure_rxTimeout = FALSE;
hs_BOOL CAN_3_0x39E_AC_temp_pressure_received = FALSE;
hs_BOOL PT_CAN_0x39E_po_ctrl_msg1_rxOverLap = TRUE;

hs_BOOL PT_CAN_0x39E_po_ctrl_msg1_rxTimeout = FALSE;
hs_BOOL PT_CAN_0x39E_po_ctrl_msg1_received = FALSE;

hs_BOOL CCP_CAN_0x729_ccpReq_rxOverLap = TRUE;
hs_u1_t CCP_CAN_0x729_ccpReq_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x729_ccpReq_rxTimeout = FALSE;
hs_BOOL CCP_CAN_0x729_ccpReq_received = FALSE;
hs_u1_t CCP_CAN_0x739_ccpRsp_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CCP_CAN_0x739_ccpRsp_txReady = FALSE;
hs_BOOL CCP_CAN_0x739_ccpRsp_txFail = FALSE;
hs_u1_t CAN_3_0x181_GW_AC_BCM_CHACAN_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x181_GW_AC_BCM_CHACAN_txReady = FALSE;
hs_BOOL CAN_3_0x181_GW_AC_BCM_CHACAN_txFail = FALSE;
hs_BOOL CAN_3_0x324_BMS_alertMatrix0_rxOverLap = TRUE;
hs_u1_t CAN_3_0x324_BMS_alertMatrix0_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x324_BMS_alertMatrix0_rxTimeout = FALSE;
hs_BOOL CAN_3_0x324_BMS_alertMatrix0_received = FALSE;
hs_BOOL CAN_3_0x334_BMS_alertMatrix1_rxOverLap = TRUE;
hs_u1_t CAN_3_0x334_BMS_alertMatrix1_rxBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x334_BMS_alertMatrix1_rxTimeout = FALSE;
hs_BOOL CAN_3_0x334_BMS_alertMatrix1_received = FALSE;
hs_u1_t CAN_3_0x330_VCU_RevV2V_txBuf[8] = {0,0,0,0,0,0,0,0};
hs_BOOL CAN_3_0x330_VCU_RevV2V_txReady = FALSE;
hs_BOOL CAN_3_0x330_VCU_RevV2V_txFail = FALSE;


/*------------------------------------------------------------------------------
                         Declaration of local functions
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                                Local data at ROM
------------------------------------------------------------------------------*/
static const canMboxCfg_t RESERVED_CANMsgCfgGrp[m_RESERVED_CAN_MsgCnt] = 
{
   /*id         msgType           msgMode              intIsr         extFrame         dir              dlc         period         txFirstDelay         rxOverlap                                                 buf                                                  rxTimeout                                                received                                                txRdy                                                  txFailed                                              pack_unpcak                                                cbHook                                               txSuccessCb                                          */
    {0x2A0,     m_can_norMsg,     m_can_eventMsg,      FALSE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                                     RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txBuf,     NULL,                                                    NULL,                                                   &RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txReady,    &RESERVED_CAN_0x2A0_can2WakeUp_display_msg_txFail,    NULL,                                                      NULL,                                                NULL                                                      },/*0[can2WakeUp_display_msg]*/
    {0x2B5,     m_can_norMsg,     m_can_eventMsg,      FALSE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxOverLap,     RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxBuf,     &RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rxTimeout,    &RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_received,    NULL,                                                  NULL,                                                 NULL,                                                      &RESERVED_CAN_0x2B5_can2Can_ComTestRec_msg_rx_cb,    NULL                                                      },/*1[can2Can_ComTestRec_msg]*/
    {0x2C5,     m_can_norMsg,     m_can_eventMsg,      FALSE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                                     RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txBuf,        NULL,                                                    NULL,                                                   &RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txReady,       &RESERVED_CAN_0x2C5_can2Can_ComTest_msg_txFail,       NULL,                                                      NULL,                                                NULL                                                      }/*2[can2Can_ComTest_msg]*/
};
static const canMboxCfg_t CLASS_CANMsgCfgGrp[m_C_CAN_MsgCnt] =
{
   /*id         msgType           msgMode              intIsr         extFrame         dir              dlc         period         txFirstDelay         rxOverlap                                                 buf                                                  rxTimeout                                                received                                                txRdy                                                  txFailed                                              pack_unpcak                                                cbHook                                               txSuccessCb                                          */
    {0x201,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          2,             0,                   NULL,                                              CCP_CAN_0x201_VCU_frontMotorTorque_txBuf,     NULL,                                             NULL,                                            &CCP_CAN_0x201_VCU_frontMotorTorque_txReady,    &CCP_CAN_0x201_VCU_frontMotorTorque_txFail,    &CCP_CAN_0x201_VCU_frontMotorTorque_txPack,         NULL,                                         &CCP_CAN_0x201_VCU_frontMotorTorque_txSuccessCb    },/*-1[VCU_frontMotorTorque]*/
    {0x211,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          2,             1,                   NULL,                                              CCP_CAN_0x211_VCU_rearMotorTorque_txBuf,      NULL,                                             NULL,                                            &CCP_CAN_0x211_VCU_rearMotorTorque_txReady,     &CCP_CAN_0x211_VCU_rearMotorTorque_txFail,     &CCP_CAN_0x211_VCU_rearMotorTorque_txPack,          NULL,                                         &CCP_CAN_0x211_VCU_rearMotorTorque_txSuccessCb     },/*-1[VCU_rearMotorTorque]*/
    {0x3A1,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            3,                   NULL,                                              CCP_CAN_0x3A1_VCU_stateCha1_txBuf,            NULL,                                             NULL,                                            &CCP_CAN_0x3A1_VCU_stateCha1_txReady,           &CCP_CAN_0x3A1_VCU_stateCha1_txFail,           &CCP_CAN_0x3A1_VCU_stateCha1_txPack,                NULL,                                         &CCP_CAN_0x3A1_VCU_stateCha1_txSuccessCb           },/*-1[VCU_stateCha1]*/
    {0x241,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          2,             2,                   NULL,                                              CCP_CAN_0x241_VCU_stateCha2_txBuf,            NULL,                                             NULL,                                            &CCP_CAN_0x241_VCU_stateCha2_txReady,           &CCP_CAN_0x241_VCU_stateCha2_txFail,           &CCP_CAN_0x241_VCU_stateCha2_txPack,                NULL,                                         &CCP_CAN_0x241_VCU_stateCha2_txSuccessCb           },/*-1[VCU_stateCha2]*/
    //{0x3B1,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            7,                   NULL,                                              CCP_CAN_0x3B1_VCU_stateCha3_txBuf,            NULL,                                             NULL,                                            &CCP_CAN_0x3B1_VCU_stateCha3_txReady,           &CCP_CAN_0x3B1_VCU_stateCha3_txFail,           &CCP_CAN_0x3B1_VCU_stateCha3_txPack,                NULL,                                         &CCP_CAN_0x3B1_VCU_stateCha3_txSuccessCb           },/*-1[VCU_stateCha3]*/
    {0x101,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1,             0,                   NULL,                                              CCP_CAN_0x101_VCU_vehicleTorque_txBuf,        NULL,                                             NULL,                                            &CCP_CAN_0x101_VCU_vehicleTorque_txReady,       &CCP_CAN_0x101_VCU_vehicleTorque_txFail,       &CCP_CAN_0x101_VCU_vehicleTorque_txPack,            NULL,                                         &CCP_CAN_0x101_VCU_vehicleTorque_txSuccessCb       },/*-1[VCU_vehicleTorque]*/
    {0x232,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x232_ESC_torqueReq_front_rxOverLap,      CCP_CAN_0x232_ESC_torqueReq_front_rxBuf,      &CCP_CAN_0x232_ESC_torqueReq_front_rxTimeout,     &CCP_CAN_0x232_ESC_torqueReq_front_received,     NULL,                                           NULL,                                          &CCP_CAN_0x232_ESC_torqueReq_front_rxUnpack,        &CCP_CAN_0x232_ESC_torqueReq_front_rx_cb,     NULL                                               },/*-1[ESC_torqueReq_front]*/
    {0x222,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x222_ESC_torqueReq_rear_rxOverLap,       CCP_CAN_0x222_ESC_torqueReq_rear_rxBuf,       &CCP_CAN_0x222_ESC_torqueReq_rear_rxTimeout,      &CCP_CAN_0x222_ESC_torqueReq_rear_received,      NULL,                                           NULL,                                          &CCP_CAN_0x222_ESC_torqueReq_rear_rxUnpack,         &CCP_CAN_0x222_ESC_torqueReq_rear_rx_cb,      NULL                                               },/*-1[ESC_torqueReq_rear]*/
    {0x58,      m_can_norMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CCP_CAN_0x58_TBOX_remoteCmd_rxOverLap,            CCP_CAN_0x58_TBOX_remoteCmd_rxBuf,            &CCP_CAN_0x58_TBOX_remoteCmd_rxTimeout,           &CCP_CAN_0x58_TBOX_remoteCmd_received,           NULL,                                           NULL,                                          &CCP_CAN_0x058_TBOX_remoteCmd_rxUnpack,             &CCP_CAN_0x58_TBOX_remoteCmd_rx_cb,           NULL                                               },/*-1[TBOX_remoteCmd]*/
    {0x3FE,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x3FE_IVI_timeAndGPS_rxOverLap,           CCP_CAN_0x3FE_IVI_timeAndGPS_rxBuf,           &CCP_CAN_0x3FE_IVI_timeAndGPS_rxTimeout,          &CCP_CAN_0x3FE_IVI_timeAndGPS_received,          NULL,                                           NULL,                                          &CCP_CAN_0x3FE_IVI_timeAndGPS_rxUnpack,             &CCP_CAN_0x3FE_IVI_timeAndGPS_rx_cb,          NULL                                               },/*-1[IVI_timeAndGPS]*/
    {0x4FE,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          100,             0,                   &CCP_CAN_0x4FE_DiagPhysReqToBMS_rxOverLap,         CCP_CAN_0x4FE_DiagPhysReqToBMS_rxBuf,         &CCP_CAN_0x4FE_DiagPhysReqToBMS_rxTimeout,        &CCP_CAN_0x4FE_DiagPhysReqToBMS_received,        NULL,                                           NULL,                                          &CCP_CAN_0x4FE_DiagPhysReqToBMS_rxUnpack,           &CCP_CAN_0x4FE_DiagPhysReqToBMS_rx_cb,        NULL                                               },/*-1[DiagPhysReqToBMS]*/
    {0xA5,      m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0xA5_IVI_pwrSet_rxOverLap,                CCP_CAN_0xA5_IVI_pwrSet_rxBuf,                &CCP_CAN_0xA5_IVI_pwrSet_rxTimeout,               &CCP_CAN_0xA5_IVI_pwrSet_received,               NULL,                                           NULL,                                          &CCP_CAN_0x0A5_IVI_pwrSet_rxUnpack,                 &CCP_CAN_0xA5_IVI_pwrSet_rx_cb,               NULL                                               },/*-1[IVI_pwrSet]*/
    {0x122,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x122_ESC_wheelSpd_Rear_rxOverLap,        CCP_CAN_0x122_ESC_wheelSpd_Rear_rxBuf,        &CCP_CAN_0x122_ESC_wheelSpd_Rear_rxTimeout,       &CCP_CAN_0x122_ESC_wheelSpd_Rear_received,       NULL,                                           NULL,                                          &CCP_CAN_0x122_ESC_wheelSpd_Rear_rxUnpack,          &CCP_CAN_0x122_ESC_wheelSpd_Rear_rx_cb,       NULL                                               },/*-1[ESC_wheelSpd_Rear]*/
    {0x124,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CCP_CAN_0x124_EPS_state_rxOverLap,                CCP_CAN_0x124_EPS_state_rxBuf,                &CCP_CAN_0x124_EPS_state_rxTimeout,               &CCP_CAN_0x124_EPS_state_received,               NULL,                                           NULL,                                          &CCP_CAN_0x124_EPS_state_rxUnpack,                  &CCP_CAN_0x124_EPS_state_rx_cb,               NULL                                               },/*-1[EPS_state]*/
    {0x142,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x142_ESC_wheelSpd_Front_rxOverLap,       CCP_CAN_0x142_ESC_wheelSpd_Front_rxBuf,       &CCP_CAN_0x142_ESC_wheelSpd_Front_rxTimeout,      &CCP_CAN_0x142_ESC_wheelSpd_Front_received,      NULL,                                           NULL,                                          &CCP_CAN_0x142_ESC_wheelSpd_Front_rxUnpack,         &CCP_CAN_0x142_ESC_wheelSpd_Front_rx_cb,      NULL                                               },/*-1[ESC_wheelSpd_Front]*/
    {0x144,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CCP_CAN_0x144_EPS_SAS_rxOverLap,                  CCP_CAN_0x144_EPS_SAS_rxBuf,                  &CCP_CAN_0x144_EPS_SAS_rxTimeout,                 &CCP_CAN_0x144_EPS_SAS_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x144_EPS_SAS_rxUnpack,                    &CCP_CAN_0x144_EPS_SAS_rx_cb,                 NULL                                               },/*-1[EPS_SAS]*/
    {0x1BE,     m_can_norMsg,     m_can_peMsg,         TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x1BE_IVI_chassisSet_rxOverLap,           CCP_CAN_0x1BE_IVI_chassisSet_rxBuf,           &CCP_CAN_0x1BE_IVI_chassisSet_rxTimeout,          &CCP_CAN_0x1BE_IVI_chassisSet_received,          NULL,                                           NULL,                                          &CCP_CAN_0x1BE_IVI_chassisSet_rxUnpack,             &CCP_CAN_0x1BE_IVI_chassisSet_rx_cb,          NULL                                               },/*-1[IVI_chassisSet]*/
    {0x1C5,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CCP_CAN_0x1C5_iB_esc1_rxOverLap,                  CCP_CAN_0x1C5_iB_esc1_rxBuf,                  &CCP_CAN_0x1C5_iB_esc1_rxTimeout,                 &CCP_CAN_0x1C5_iB_esc1_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x1C5_iB_esc1_rxUnpack,                    &CCP_CAN_0x1C5_iB_esc1_rx_cb,                 NULL                                               },/*-1[iB_esc1]*/
    {0x1D5,     m_can_norMsg,     m_can_peMsg,         TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x1D5_GW_icm_ivi_rxOverLap,               CCP_CAN_0x1D5_GW_icm_ivi_rxBuf,               &CCP_CAN_0x1D5_GW_icm_ivi_rxTimeout,              &CCP_CAN_0x1D5_GW_icm_ivi_received,              NULL,                                           NULL,                                          &CCP_CAN_0x1D5_GW_icm_ivi_rxUnpack,                 &CCP_CAN_0x1D5_GW_icm_ivi_rx_cb,              NULL                                               },/*-1[GW_icm_ivi]*/
    {0x212,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x212_ESC_state1_rxOverLap,               CCP_CAN_0x212_ESC_state1_rxBuf,               &CCP_CAN_0x212_ESC_state1_rxTimeout,              &CCP_CAN_0x212_ESC_state1_received,              NULL,                                           NULL,                                          &CCP_CAN_0x212_ESC_state1_rxUnpack,                 NULL,                                         NULL                                               },/*-1[ESC_state1]*/
    {0x219,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x219_MRR_acc_rxOverLap,                  CCP_CAN_0x219_MRR_acc_rxBuf,                  &CCP_CAN_0x219_MRR_acc_rxTimeout,                 &CCP_CAN_0x219_MRR_acc_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x219_MRR_acc_rxUnpack,                    &CCP_CAN_0x219_MRR_acc_rx_cb,                 NULL                                               },/*-1[MRR_acc]*/
    {0x21A,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x21A_MPC_state_rxOverLap,                CCP_CAN_0x21A_MPC_state_rxBuf,                &CCP_CAN_0x21A_MPC_state_rxTimeout,               &CCP_CAN_0x21A_MPC_state_received,               NULL,                                           NULL,                                          &CCP_CAN_0x21A_MPC_state_rxUnpack,                  &CCP_CAN_0x21A_MPC_state_rx_cb,               NULL                                               },/*-1[MPC_state]*/
    {0x242,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x242_ESC_apaSet_rxOverLap,               CCP_CAN_0x242_ESC_apaSet_rxBuf,               &CCP_CAN_0x242_ESC_apaSet_rxTimeout,              &CCP_CAN_0x242_ESC_apaSet_received,              NULL,                                           NULL,                                          &CCP_CAN_0x242_ESC_apaSet_rxUnpack,                 &CCP_CAN_0x242_ESC_apaSet_rx_cb,              NULL                                               },/*-1[ESC_apaSet]*/
    {0x252,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x252_ESC_yawState_rxOverLap,             CCP_CAN_0x252_ESC_yawState_rxBuf,             &CCP_CAN_0x252_ESC_yawState_rxTimeout,            &CCP_CAN_0x252_ESC_yawState_received,            NULL,                                           NULL,                                          &CCP_CAN_0x252_ESC_yawState_rxUnpack,               &CCP_CAN_0x252_ESC_yawState_rx_cb,            NULL                                               },/*-1[ESC_yawState]*/
    {0x272,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x272_ESC_wssFront_rxOverLap,             CCP_CAN_0x272_ESC_wssFront_rxBuf,             &CCP_CAN_0x272_ESC_wssFront_rxTimeout,            &CCP_CAN_0x272_ESC_wssFront_received,            NULL,                                           NULL,                                          &CCP_CAN_0x272_ESC_wssFront_rxUnpack,               &CCP_CAN_0x272_ESC_wssFront_rx_cb,            NULL                                               },/*-1[ESC_wssFront]*/
    {0x282,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x282_ESC_wssRear_rxOverLap,              CCP_CAN_0x282_ESC_wssRear_rxBuf,              &CCP_CAN_0x282_ESC_wssRear_rxTimeout,             &CCP_CAN_0x282_ESC_wssRear_received,             NULL,                                           NULL,                                          &CCP_CAN_0x282_ESC_wssRear_rxUnpack,                &CCP_CAN_0x282_ESC_wssRear_rx_cb,             NULL                                               },/*-1[ESC_wssRear]*/
    {0x2A1,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2A1_TSV31_rxOverLap,                    CCP_CAN_0x2A1_TSV31_rxBuf,                    &CCP_CAN_0x2A1_TSV31_rxTimeout,                   &CCP_CAN_0x2A1_TSV31_received,                   NULL,                                           NULL,                                          &CCP_CAN_0x2A1_TSV31_rxUnpack,                      &CCP_CAN_0x2A1_TSV31_rx_cb,                   NULL                                               },/*-1[TSV31]*/
    {0x2A2,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2A2_ESC_state2_rxOverLap,               CCP_CAN_0x2A2_ESC_state2_rxBuf,               &CCP_CAN_0x2A2_ESC_state2_rxTimeout,              &CCP_CAN_0x2A2_ESC_state2_received,              NULL,                                           NULL,                                          &CCP_CAN_0x2A2_ESC_state2_rxUnpack,                 &CCP_CAN_0x2A2_ESC_state2_rx_cb,              NULL                                               },/*-1[ESC_state2]*/
    {0x2A5,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2A5_iB_esc2_rxOverLap,                  CCP_CAN_0x2A5_iB_esc2_rxBuf,                  &CCP_CAN_0x2A5_iB_esc2_rxTimeout,                 &CCP_CAN_0x2A5_iB_esc2_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x2A5_iB_esc2_rxUnpack,                    &CCP_CAN_0x2A5_iB_esc2_rx_cb,                 NULL                                               },/*-1[iB_esc2]*/
    {0x2C2,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2C2_ESC_epb_rxOverLap,                  CCP_CAN_0x2C2_ESC_epb_rxBuf,                  &CCP_CAN_0x2C2_ESC_epb_rxTimeout,                 &CCP_CAN_0x2C2_ESC_epb_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x2C2_ESC_epb_rxUnpack,                    &CCP_CAN_0x2C2_ESC_epb_rx_cb,                 NULL                                               },/*-1[ESC_epb]*/
    {0x2CE,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2CE_BCM_peps_rxOverLap,                 CCP_CAN_0x2CE_BCM_peps_rxBuf,                 &CCP_CAN_0x2CE_BCM_peps_rxTimeout,                &CCP_CAN_0x2CE_BCM_peps_received,                NULL,                                           NULL,                                          &CCP_CAN_0x2CE_BCM_peps_rxUnpack,                   &CCP_CAN_0x2CE_BCM_peps_rx_cb,                NULL                                               },/*-1[BCM_peps]*/
    {0x2FE,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CCP_CAN_0x2FE_IC_state_rxOverLap,                 CCP_CAN_0x2FE_IC_state_rxBuf,                 &CCP_CAN_0x2FE_IC_state_rxTimeout,                &CCP_CAN_0x2FE_IC_state_received,                NULL,                                           NULL,                                          &CCP_CAN_0x2FE_IC_state_rxUnpack,                   &CCP_CAN_0x2FE_IC_state_rx_cb,                NULL                                               },/*-1[IC_state]*/
    {0x319,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x319_SWM_Set_rxOverLap,                  CCP_CAN_0x319_SWM_Set_rxBuf,                  &CCP_CAN_0x319_SWM_Set_rxTimeout,                 &CCP_CAN_0x319_SWM_Set_received,                 NULL,                                           NULL,                                          &CCP_CAN_0x319_SWM_Set_rxUnpack,                    &CCP_CAN_0x319_SWM_Set_rx_cb,                 NULL                                               },/*-1[SWM_Set]*/
    {0x341,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x341_ASC_state1_rxOverLap,               CCP_CAN_0x341_ASC_state1_rxBuf,               &CCP_CAN_0x341_ASC_state1_rxTimeout,              &CCP_CAN_0x341_ASC_state1_received,              NULL,                                           NULL,                                          &CCP_CAN_0x341_ASC_state1_rxUnpack,                 &CCP_CAN_0x341_ASC_state1_rx_cb,              NULL                                               },/*-1[ASC_state1]*/
    {0x380,     m_can_norMsg,     m_can_peMsg,         TRUE,         FALSE,           m_can_dirRx,     8,          5,             0,                   &CCP_CAN_0x380_ACU_state_rxOverLap,                CCP_CAN_0x380_ACU_state_rxBuf,                &CCP_CAN_0x380_ACU_state_rxTimeout,               &CCP_CAN_0x380_ACU_state_received,               NULL,                                           NULL,                                          &CCP_CAN_0x380_ACU_state_rxUnpack,                  &CCP_CAN_0x380_ACU_state_rx_cb,               NULL                                               },/*-1[ACU_state]*/
    {0x39E,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxOverLap,         CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxBuf,         &CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxTimeout,        &CCP_CAN_0x39E_GW_AC_BCM_CHACAN_received,        NULL,                                           NULL,                                          &CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rxUnpack,           &CCP_CAN_0x39E_GW_AC_BCM_CHACAN_rx_cb,        NULL                                               }/*-1[GW_AC_BCM_CHACAN]*/

};

static const canMboxCfg_t PT_CANMsgCfgGrp[m_PT_CAN_MsgCnt] = 
{
   /*id         msgType           msgMode              intIsr         extFrame         dir              dlc         period         txFirstDelay         rxOverlap                                          buf                                           rxTimeout                                         received                                         txRdy                                           txFailed                                       pack_unpcak                                         cbHook                                        txSuccessCb                                   */
	{0x5F1,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1,           0,                   NULL,                                              CAN_3_0x5F1_VCU_version_txBuf,                NULL,                                             NULL,                                            &CAN_3_0x5F1_VCU_version_txReady,               &CAN_3_0x5F1_VCU_version_txFail,               &CAN_3_0x5F1_VCU_version_txPack,                    NULL,                                         &CAN_3_0x5F1_VCU_version_txSuccessCb               },/*19[VCU_version]*/
	{0x181,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1,             1,                   NULL,                                              CAN_3_0x181_GW_AC_BCM_CHACAN_txBuf,           NULL,                                             NULL,                                            &CAN_3_0x181_GW_AC_BCM_CHACAN_txReady,          &CAN_3_0x181_GW_AC_BCM_CHACAN_txFail,          &CAN_3_0x181_GW_AC_BCM_CHACAN_txPack,               NULL,          &CAN_3_0x181_GW_AC_BCM_CHACAN_txSuccessCb                                               },/*62[GW_AC_BCM_CHACAN]*/
	{0x101,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1,             0,                   NULL,                                              CAN_3_0x101_VCU_torque_txBuf,                 NULL,                                             NULL,                                            &CAN_3_0x101_VCU_torque_txReady,                &CAN_3_0x101_VCU_torque_txFail,                &CAN_3_0x101_VCU_torque_txPack,                     NULL,                                         &CAN_3_0x101_VCU_torque_txSuccessCb                },/*20[VCU_torque]*/
    {0x111,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1,             1,                   NULL,                                              CAN_3_0x111_VCU_state_txBuf,                  NULL,                                             NULL,                                            &CAN_3_0x111_VCU_state_txReady,                 &CAN_3_0x111_VCU_state_txFail,                 &CAN_3_0x111_VCU_state_txPack,                      NULL,                                         &CAN_3_0x111_VCU_state_txSuccessCb                 },/*14[VCU_state]*/
	{0x301,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            2,                   NULL,                                              CAN_3_0x301_VCU_pwr_txBuf,                    NULL,                                             NULL,                                            &CAN_3_0x301_VCU_pwr_txReady,                   &CAN_3_0x301_VCU_pwr_txFail,                   &CAN_3_0x301_VCU_pwr_txPack,                        NULL,                                         &CAN_3_0x301_VCU_pwr_txSuccessCb                   },/*0[VCU_pwr]*/
    {0x302,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             3,                   &CAN_3_0x302_MCUR0_temperature_rxOverLap,          CAN_3_0x302_MCUR0_temperature_rxBuf,          &CAN_3_0x302_MCUR0_temperature_rxTimeout,         &CAN_3_0x302_MCUR0_temperature_received,         NULL,                                           NULL,                                          &CAN_3_0x302_MCUR0_temperature_rxUnpack,            &CAN_3_0x302_MCUR0_temperature_rx_cb,         NULL                                               },/*1[MCUR0_temperature]*/
    {0x303,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             5,                   &CAN_3_0x303_MCUF0_temperature_rxOverLap,          CAN_3_0x303_MCUF0_temperature_rxBuf,          &CAN_3_0x303_MCUF0_temperature_rxTimeout,         &CAN_3_0x303_MCUF0_temperature_received,         NULL,                                           NULL,                                          &CAN_3_0x303_MCUF0_temperature_rxUnpack,            &CAN_3_0x303_MCUF0_temperature_rx_cb,         NULL                                               },/*2[MCUF0_temperature]*/
    {0x304,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             7,                   &CAN_3_0x304_BMS_temperature_rxOverLap,            CAN_3_0x304_BMS_temperature_rxBuf,            &CAN_3_0x304_BMS_temperature_rxTimeout,           &CAN_3_0x304_BMS_temperature_received,           NULL,                                           NULL,                                          &CAN_3_0x304_BMS_temperature_rxUnpack,              &CAN_3_0x304_BMS_temperature_rx_cb,           NULL                                               },/*3[BMS_temperature]*/
    {0x5A4,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          50,            11,                   NULL,                                              CAN_3_0x5A4_VCU_DutyCycle_txBuf,              NULL,                                             NULL,                                            &CAN_3_0x5A4_VCU_DutyCycle_txReady,             &CAN_3_0x5A4_VCU_DutyCycle_txFail,             &CAN_3_0x5A4_VCU_DutyCycle_txPack,                  NULL,                                         &CAN_3_0x5A4_VCU_DutyCycle_txSuccessCb             },/*4[VCU_DutyCycle]*/
	{0x2FA,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            6,                   NULL,                                              CAN_3_0x2FA_VCU_Indication_txBuf,             NULL,                                             NULL,                                            &CAN_3_0x2FA_VCU_Indication_txReady,            &CAN_3_0x2FA_VCU_Indication_txFail,            &CAN_3_0x2FA_VCU_Indication_txPack,                 NULL,                                         &CAN_3_0x2FA_VCU_Indication_txSuccessCb            },/*6[VCU_Indication]*/
    {0x5A5,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          50,            23,                   NULL,                                              CAN_3_0x5A5_VCU_PTCPower_txBuf,               NULL,                                             NULL,                                            &CAN_3_0x5A5_VCU_PTCPower_txReady,              &CAN_3_0x5A5_VCU_PTCPower_txFail,              &CAN_3_0x5A5_VCU_PTCPower_txPack,                   NULL,                                         &CAN_3_0x5A5_VCU_PTCPower_txSuccessCb              },/*7[VCU_PTCPower]*/
    {0x331,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            9,                   NULL,                                              CAN_3_0x331_VCU_Rev_txBuf,                    NULL,                                             NULL,                                            &CAN_3_0x331_VCU_Rev_txReady,                   &CAN_3_0x331_VCU_Rev_txFail,                   &CAN_3_0x331_VCU_Rev_txPack,                        NULL,                                         &CAN_3_0x331_VCU_Rev_txSuccessCb                   },/*8[VCU_Rev]*/
	{0x321,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            0,                   NULL,                                              CAN_3_0x321_VCU_alertMatrix0_txBuf,           NULL,                                             NULL,                                            &CAN_3_0x321_VCU_alertMatrix0_txReady,          &CAN_3_0x321_VCU_alertMatrix0_txFail,          &CAN_3_0x321_VCU_alertMatrix0_txPack,               NULL,                                         &CAN_3_0x321_VCU_alertMatrix0_txSuccessCb          },/*11[VCU_alertMatrix0]*/
    {0x561,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          100,          33,                   NULL,                                              CAN_3_0x561_VCU_range_txBuf,                  NULL,                                             NULL,                                            &CAN_3_0x561_VCU_range_txReady,                 &CAN_3_0x561_VCU_range_txFail,                 &CAN_3_0x561_VCU_range_txPack,                      NULL,                                         &CAN_3_0x561_VCU_range_txSuccessCb                 },/*12[VCU_range]*/
    {0x551,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          1000,          0,                   NULL,                                              CAN_3_0x551_VCU_standard_txBuf,               NULL,                                             NULL,                                            &CAN_3_0x551_VCU_standard_txReady,              &CAN_3_0x551_VCU_standard_txFail,              &CAN_3_0x551_VCU_standard_txPack,                   NULL,                                         &CAN_3_0x551_VCU_standard_txSuccessCb              },/*13[VCU_standard]*/
	{0x401,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          20,            17,                   NULL,                                              CAN_3_0x401_VCU_subPower_txBuf,               NULL,                                             NULL,                                            &CAN_3_0x401_VCU_subPower_txReady,              &CAN_3_0x401_VCU_subPower_txFail,              &CAN_3_0x401_VCU_subPower_txPack,                   NULL,                                         &CAN_3_0x401_VCU_subPower_txSuccessCb              },/*15[VCU_subPower]*/
    {0x511,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          100,          1,                   NULL,                                              CAN_3_0x511_VCU_tboxGeneralAlert_txBuf,       NULL,                                             NULL,                                            &CAN_3_0x511_VCU_tboxGeneralAlert_txReady,      &CAN_3_0x511_VCU_tboxGeneralAlert_txFail,      &CAN_3_0x511_VCU_tboxGeneralAlert_txPack,           NULL,                                         &CAN_3_0x511_VCU_tboxGeneralAlert_txSuccessCb      },/*16[VCU_tboxGeneralAlert]*/
    {0x521,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          100,           11,                   NULL,                                              CAN_3_0x521_VCU_thermal_txBuf,                NULL,                                             NULL,                                            &CAN_3_0x521_VCU_thermal_txReady,               &CAN_3_0x521_VCU_thermal_txFail,               &CAN_3_0x521_VCU_thermal_txPack,                    NULL,                                         &CAN_3_0x521_VCU_thermal_txSuccessCb               },/*17[VCU_thermal]*/
    {0x531,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          100,           6,                   NULL,                                              CAN_3_0x531_VCU_thermal2_txBuf,               NULL,                                             NULL,                                            &CAN_3_0x531_VCU_thermal2_txReady,              &CAN_3_0x531_VCU_thermal2_txFail,              &CAN_3_0x531_VCU_thermal2_txPack,                   NULL,                                         &CAN_3_0x531_VCU_thermal2_txSuccessCb              },/*18[VCU_thermal2]*/
	{0x441,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            7,                   NULL,                                              CAN_3_0x441_VCU_vehicle_txBuf,                NULL,                                             NULL,                                            &CAN_3_0x441_VCU_vehicle_txReady,               &CAN_3_0x441_VCU_vehicle_txFail,               &CAN_3_0x441_VCU_vehicle_txPack,                    NULL,                                         &CAN_3_0x441_VCU_vehicle_txSuccessCb               },/*21[VCU_vehicle]*/
    {0x3A6,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x3A6_AC_pwtAlloted_rxOverLap,              CAN_3_0x3A6_AC_pwtAlloted_rxBuf,              &CAN_3_0x3A6_AC_pwtAlloted_rxTimeout,             &CAN_3_0x3A6_AC_pwtAlloted_received,             NULL,                                           NULL,                                          &CAN_3_0x3A6_AC_pwtAlloted_rxUnpack,                &CAN_3_0x3A6_AC_pwtAlloted_rx_cb,             NULL                                               },/*22[AC_pwtAlloted]*/
	{0x731,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x731_Diag_PhyReq_VCU_rxOverLap,            CAN_3_0x731_Diag_PhyReq_VCU_rxBuf,            &CAN_3_0x731_Diag_PhyReq_VCU_rxTimeout,           &CAN_3_0x731_Diag_PhyReq_VCU_received,           NULL,                                           NULL,                                          NULL,                                               &CAN_3_0x731_Diag_PhyReq_VCU_rx_cb,           NULL                                               },/*23[Diag_PhyReq_VCU]*/
    {0x7E7,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x7E7_OBD_PhyReq_VCU_rxOverLap,             CAN_3_0x7E7_OBD_PhyReq_VCU_rxBuf,             &CAN_3_0x7E7_OBD_PhyReq_VCU_rxTimeout,            &CAN_3_0x7E7_OBD_PhyReq_VCU_received,            NULL,                                           NULL,                                          NULL,                                               &CAN_3_0x7E7_OBD_PhyReq_VCU_rx_cb,            NULL                                               },/*24[OBD_PhyReq_VCU]*/
    {0x7DF,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x7DF_Diag_FuncReq_rxOverLap,               CAN_3_0x7DF_Diag_FuncReq_rxBuf,               &CAN_3_0x7DF_Diag_FuncReq_rxTimeout,              &CAN_3_0x7DF_Diag_FuncReq_received,              NULL,                                           NULL,                                          NULL,                                               &CAN_3_0x7DF_Diag_FuncReq_rx_cb,              NULL                                               },/*25[Diag_FuncReq]*/
    {0x330,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirTx,     8,          10,            0,                   NULL,                                              CAN_3_0x330_VCU_RevV2V_txBuf,                 NULL,                                             NULL,                                            &CAN_3_0x330_VCU_RevV2V_txReady,                &CAN_3_0x330_VCU_RevV2V_txFail,                &CAN_3_0x330_VCU_RevV2V_txPack,                     &CAN_3_0x330_VCU_RevV2V_tx_cb,                NULL                                               },/*65[VCU_RevV2V]*/
	{0x797,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x797_CCP_Rx_rxOverLap,                     CAN_3_0x797_CCP_Rx_rxBuf,                     &CAN_3_0x797_CCP_Rx_rxTimeout,                    &CAN_3_0x797_CCP_Rx_received,                    NULL,                                           NULL,                                          NULL,                                               &CAN_3_0x797_CCP_Rx_rx_cb,                    NULL                                               },/*27[CCP_Rx]*/
    {0x7B1,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                              CAN_3_0x7B1_Diag_Resp_VCU_txBuf,              NULL,                                             NULL,                                            &CAN_3_0x7B1_Diag_Resp_VCU_txReady,             &CAN_3_0x7B1_Diag_Resp_VCU_txFail,             NULL,                                               NULL,                                         &CAN_3_0x7B1_Diag_Resp_VCU_txSuccessCb             },/*28[Diag_Resp_VCU]*/
    {0x7EF,     m_can_udsMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                              CAN_3_0x7EF_OBD_Resp_VCU_txBuf,               NULL,                                             NULL,                                            &CAN_3_0x7EF_OBD_Resp_VCU_txReady,              &CAN_3_0x7EF_OBD_Resp_VCU_txFail,              NULL,                                               NULL,                                         &CAN_3_0x7EF_OBD_Resp_VCU_txSuccessCb              },/*29[OBD_Resp_VCU]*/
    {0x3F3,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          100,            0,                   &CAN_3_0x3F3_IC_info_rxOverLap,                    CAN_3_0x3F3_IC_info_rxBuf,                    &CAN_3_0x3F3_IC_info_rxTimeout,                   &CAN_3_0x3F3_IC_info_received,                   NULL,                                           NULL,                                          &CAN_3_0x3F3_IC_info_rxUnpack,                      &CAN_3_0x3F3_IC_info_rx_cb,                   NULL                                               },/*30[IC_info]*/
    {0x492,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          50,             0,                   &CAN_3_0x492_IC_state2_rxOverLap,                  CAN_3_0x492_IC_state2_rxBuf,                  &CAN_3_0x492_IC_state2_rxTimeout,                 &CAN_3_0x492_IC_state2_received,                 NULL,                                           NULL,                                          &CAN_3_0x492_IC_state2_rxUnpack,                    &CAN_3_0x492_IC_state2_rx_cb,                 NULL                                               },/*31[IC_state2]*/
    {0x394,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x394_POT_state_rxOverLap,                  CAN_3_0x394_POT_state_rxBuf,                  &CAN_3_0x394_POT_state_rxTimeout,                 &CAN_3_0x394_POT_state_received,                 NULL,                                           NULL,                                          &CAN_3_0x394_POT_state_rxUnpack,                    &CAN_3_0x394_POT_state_rx_cb,                 NULL                                               },/*32[POT_state]*/
    {0x407,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          20,             0,                   &CAN_3_0x407_OBC_state1_rxOverLap,                 CAN_3_0x407_OBC_state1_rxBuf,                 &CAN_3_0x407_OBC_state1_rxTimeout,                &CAN_3_0x407_OBC_state1_received,                NULL,                                           NULL,                                          &CAN_3_0x407_OBC_state1_rxUnpack,                   &CAN_3_0x407_OBC_state1_rx_cb,                NULL                                               },/*33[OBC_state1]*/
    {0x487,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          50,             0,                   &CAN_3_0x487_OBC_state2_rxOverLap,                 CAN_3_0x487_OBC_state2_rxBuf,                 &CAN_3_0x487_OBC_state2_rxTimeout,                &CAN_3_0x487_OBC_state2_received,                NULL,                                           NULL,                                          &CAN_3_0x487_OBC_state2_rxUnpack,                   &CAN_3_0x487_OBC_state2_rx_cb,                NULL                                               },/*34[OBC_state2]*/
    {0x75,      m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x75_IVI_control_rxOverLap,                 CAN_3_0x75_IVI_control_rxBuf,                 &CAN_3_0x75_IVI_control_rxTimeout,                &CAN_3_0x75_IVI_control_received,                NULL,                                           NULL,                                          &CAN_3_0x075_IVI_control_rxUnpack,                  &CAN_3_0x75_IVI_control_rx_cb,                NULL                                               },/*35[IVI_control]*/
    {0x7E,      m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x7E_TBOX_chargeSet_rxOverLap,              CAN_3_0x7E_TBOX_chargeSet_rxBuf,              &CAN_3_0x7E_TBOX_chargeSet_rxTimeout,             &CAN_3_0x7E_TBOX_chargeSet_received,             NULL,                                           NULL,                                          &CAN_3_0x07E_TBOX_chargeSet_rxUnpack,               &CAN_3_0x7E_TBOX_chargeSet_rx_cb,             NULL                                               },/*36[TBOX_chargeSet]*/
    {0x4FE,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          100,            0,                   &CAN_3_0x4FE_TBOX_VehicleMode_rxOverLap,           CAN_3_0x4FE_TBOX_VehicleMode_rxBuf,           &CAN_3_0x4FE_TBOX_VehicleMode_rxTimeout,          &CAN_3_0x4FE_TBOX_VehicleMode_received,          NULL,                                           NULL,                                          &CAN_3_0x4FE_TBOX_VehicleMode_rxUnpack,             &CAN_3_0x4FE_TBOX_VehicleMode_rx_cb,          NULL                                               },/*37[TBOX_VehicleMode]*/
    {0x514,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          100,            0,                   &CAN_3_0x514_BMS_metric_rxOverLap,                 CAN_3_0x514_BMS_metric_rxBuf,                 &CAN_3_0x514_BMS_metric_rxTimeout,                &CAN_3_0x514_BMS_metric_received,                NULL,                                           NULL,                                          &CAN_3_0x514_BMS_metric_rxUnpack,                   &CAN_3_0x514_BMS_metric_rx_cb,                NULL                                               },/*38[BMS_metric]*/
    {0x574,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          100,            0,                   &CAN_3_0x574_BMS_tboxRequest_rxOverLap,            CAN_3_0x574_BMS_tboxRequest_rxBuf,            &CAN_3_0x574_BMS_tboxRequest_rxTimeout,           &CAN_3_0x574_BMS_tboxRequest_received,           NULL,                                           NULL,                                          &CAN_3_0x574_BMS_tboxRequest_rxUnpack,              &CAN_3_0x574_BMS_tboxRequest_rx_cb,           NULL                                               },/*39[BMS_tboxRequest]*/
    {0x631,     m_can_nmMsg,      m_can_eventMsg,      TRUE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                              CAN_3_0x631_NM_VCU_txBuf,                     NULL,                                             NULL,                                            &CAN_3_0x631_NM_VCU_txReady,                    &CAN_3_0x631_NM_VCU_txFail,                    &CAN_3_0x631_NM_VCU_txPack,                         &CAN_3_0x631_NM_VCU_tx_cb,                    &CAN_3_0x631_NM_VCU_txSuccessCb                                               },/*40[NM_VCU]*/
    {0x632,     m_can_nmMsg,      m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x632_NM_MCUR0_rxOverLap,                   CAN_3_0x632_NM_MCUR0_rxBuf,                   &CAN_3_0x632_NM_MCUR0_rxTimeout,                  &CAN_3_0x632_NM_MCUR0_received,                  NULL,                                           NULL,                                          &CAN_3_0x632_NM_MCUR0_rxUnpack,                     &CAN_3_0x632_NM_MCUR0_rx_cb,                  NULL                                               },/*41[NM_MCUR0]*/
    {0x634,     m_can_nmMsg,      m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x634_NM_BMS_rxOverLap,                     CAN_3_0x634_NM_BMS_rxBuf,                     &CAN_3_0x634_NM_BMS_rxTimeout,                    &CAN_3_0x634_NM_BMS_received,                    NULL,                                           NULL,                                          &CAN_3_0x634_NM_BMS_rxUnpack,                       &CAN_3_0x634_NM_BMS_rx_cb,                    NULL                                               },/*42[NM_BMS]*/
    {0x637,     m_can_nmMsg,      m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x637_NM_OBCM_rxOverLap,                    CAN_3_0x637_NM_OBCM_rxBuf,                    &CAN_3_0x637_NM_OBCM_rxTimeout,                   &CAN_3_0x637_NM_OBCM_received,                   NULL,                                           NULL,                                          &CAN_3_0x637_NM_OBCM_rxUnpack,                      &CAN_3_0x637_NM_OBCM_rx_cb,                   NULL                                               },/*43[NM_OBCM]*/
    {0x63E,     m_can_nmMsg,      m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CAN_3_0x63E_NM_GW_PT_rxOverLap,                   CAN_3_0x63E_NM_GW_PT_rxBuf,                   &CAN_3_0x63E_NM_GW_PT_rxTimeout,                  &CAN_3_0x63E_NM_GW_PT_received,                  NULL,                                           NULL,                                          &CAN_3_0x63E_NM_GW_PT_rxUnpack,                     &CAN_3_0x63E_NM_GW_PT_rx_cb,                  NULL                                               },/*44[NM_GW_PT]*/
    {0x102,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x102_MCUR0_torque_rxOverLap,               CAN_3_0x102_MCUR0_torque_rxBuf,               &CAN_3_0x102_MCUR0_torque_rxTimeout,              &CAN_3_0x102_MCUR0_torque_received,              NULL,                                           NULL,                                          &CAN_3_0x102_MCUR0_torque_rxUnpack,                 &CAN_3_0x102_MCUR0_torque_rx_cb,              NULL                                               },/*45[MCUR0_torque]*/
    {0x103,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x103_MCUF0_torque_rxOverLap,               CAN_3_0x103_MCUF0_torque_rxBuf,               &CAN_3_0x103_MCUF0_torque_rxTimeout,              &CAN_3_0x103_MCUF0_torque_received,              NULL,                                           NULL,                                          &CAN_3_0x103_MCUF0_torque_rxUnpack,                 &CAN_3_0x103_MCUF0_torque_rx_cb,              NULL                                               },/*46[MCUF0_torque]*/
    {0x104,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x104_BMS_meas_rxOverLap,                   CAN_3_0x104_BMS_meas_rxBuf,                   &CAN_3_0x104_BMS_meas_rxTimeout,                  &CAN_3_0x104_BMS_meas_received,                  NULL,                                           NULL,                                          &CAN_3_0x104_BMS_meas_rxUnpack,                     &CAN_3_0x104_BMS_meas_rx_cb,                  NULL                                               },/*47[BMS_meas]*/
    {0x112,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x112_MCUR0_state_rxOverLap,                CAN_3_0x112_MCUR0_state_rxBuf,                &CAN_3_0x112_MCUR0_state_rxTimeout,               &CAN_3_0x112_MCUR0_state_received,               NULL,                                           NULL,                                          &CAN_3_0x112_MCUR0_state_rxUnpack,                  &CAN_3_0x112_MCUR0_state_rx_cb,               NULL                                               },/*48[MCUR0_state]*/
    {0x113,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x113_MCUF0_state_rxOverLap,                CAN_3_0x113_MCUF0_state_rxBuf,                &CAN_3_0x113_MCUF0_state_rxTimeout,               &CAN_3_0x113_MCUF0_state_received,               NULL,                                           NULL,                                          &CAN_3_0x113_MCUF0_state_rxUnpack,                  &CAN_3_0x113_MCUF0_state_rx_cb,               NULL                                               },/*49[MCUF0_state]*/
    {0x114,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x114_BMS_state_rxOverLap,                  CAN_3_0x114_BMS_state_rxBuf,                  &CAN_3_0x114_BMS_state_rxTimeout,                 &CAN_3_0x114_BMS_state_received,                 NULL,                                           NULL,                                          &CAN_3_0x114_BMS_state_rxUnpack,                    &CAN_3_0x114_BMS_state_rx_cb,                 NULL                                               },/*50[BMS_state]*/
    {0x126,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x126_BMS_RevFaultInfo_rxOverLap,           CAN_3_0x126_BMS_RevFaultInfo_rxBuf,           &CAN_3_0x126_BMS_RevFaultInfo_rxTimeout,          &CAN_3_0x126_BMS_RevFaultInfo_received,          NULL,                                           NULL,                                          &CAN_3_0x126_BMS_RevFaultInfo_rxUnpack,             &CAN_3_0x126_BMS_RevFaultInfo_rx_cb,          NULL                                               },/*51[BMS_RevFaultInfo]*/
    {0x134,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          1,             0,                   &CAN_3_0x134_BMS_driveLimits_rxOverLap,            CAN_3_0x134_BMS_driveLimits_rxBuf,            &CAN_3_0x134_BMS_driveLimits_rxTimeout,           &CAN_3_0x134_BMS_driveLimits_received,           NULL,                                           NULL,                                          &CAN_3_0x134_BMS_driveLimits_rxUnpack,              &CAN_3_0x134_BMS_driveLimits_rx_cb,           NULL                                               },/*52[BMS_driveLimits]*/
    {0x2C1,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CAN_3_0x2C1_BCM_peps_rxOverLap,                   CAN_3_0x2C1_BCM_peps_rxBuf,                   &CAN_3_0x2C1_BCM_peps_rxTimeout,                  &CAN_3_0x2C1_BCM_peps_received,                  NULL,                                           NULL,                                          &CAN_3_0x2C1_BCM_peps_rxUnpack,                     &CAN_3_0x2C1_BCM_peps_rx_cb,                  NULL                                               },/*53[BCM_peps]*/
    {0x309,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          2,             0,                   &CAN_3_0x309_GSM_state_rxOverLap,                  CAN_3_0x309_GSM_state_rxBuf,                  &CAN_3_0x309_GSM_state_rxTimeout,                 &CAN_3_0x309_GSM_state_received,                 NULL,                                           NULL,                                          &CAN_3_0x309_GSM_state_rxUnpack,                    &CAN_3_0x309_GSM_state_rx_cb,                 NULL                                               },/*54[GSM_state]*/
    {0x312,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x312_MCUR0_state2_rxOverLap,               CAN_3_0x312_MCUR0_state2_rxBuf,               &CAN_3_0x312_MCUR0_state2_rxTimeout,              &CAN_3_0x312_MCUR0_state2_received,              NULL,                                           NULL,                                          &CAN_3_0x312_MCUR0_state2_rxUnpack,                 &CAN_3_0x312_MCUR0_state2_rx_cb,              NULL                                               },/*55[MCUR0_state2]*/
    {0x313,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x313_MCUF0_state2_rxOverLap,               CAN_3_0x313_MCUF0_state2_rxBuf,               &CAN_3_0x313_MCUF0_state2_rxTimeout,              &CAN_3_0x313_MCUF0_state2_received,              NULL,                                           NULL,                                          &CAN_3_0x313_MCUF0_state2_rxUnpack,                 &CAN_3_0x313_MCUF0_state2_rx_cb,              NULL                                               },/*56[MCUF0_state2]*/
	{0x324,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x324_BMS_alertMatrix0_rxOverLap,           CAN_3_0x324_BMS_alertMatrix0_rxBuf,           &CAN_3_0x324_BMS_alertMatrix0_rxTimeout,          &CAN_3_0x324_BMS_alertMatrix0_received,          NULL,                                           NULL,                                          &CAN_3_0x324_BMS_alertMatrix0_rxUnpack,             &CAN_3_0x324_BMS_alertMatrix0_rx_cb,          NULL                                               },/*63[BMS_alertMatrix0]*/
    {0x387,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x387_OBC_state_rxOverLap,                  CAN_3_0x387_OBC_state_rxBuf,                  &CAN_3_0x387_OBC_state_rxTimeout,                 &CAN_3_0x387_OBC_state_received,                 NULL,                                           NULL,                                          &CAN_3_0x387_OBC_state_rxUnpack,                    &CAN_3_0x387_OBC_state_rx_cb,                 NULL                                               },/*58[OBC_state]*/
    {0x38D,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x38D_DCDC_state_rxOverLap,                 CAN_3_0x38D_DCDC_state_rxBuf,                 &CAN_3_0x38D_DCDC_state_rxTimeout,                &CAN_3_0x38D_DCDC_state_received,                NULL,                                           NULL,                                          &CAN_3_0x38D_DCDC_state_rxUnpack,                   &CAN_3_0x38D_DCDC_state_rx_cb,                NULL                                               },/*59[DCDC_state]*/
    {0x38E,     m_can_norMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          5,             0,                   &CAN_3_0x38E_ACU_state_rxOverLap,                  CAN_3_0x38E_ACU_state_rxBuf,                  &CAN_3_0x38E_ACU_state_rxTimeout,                 &CAN_3_0x38E_ACU_state_received,                 NULL,                                           NULL,                                          &CAN_3_0x38E_ACU_state_rxUnpack,                    &CAN_3_0x38E_ACU_state_rx_cb,                 NULL                                               },/*60[ACU_state]*/
    {0x39E,     m_can_norMsg,     m_can_periodMsg,     TRUE,         FALSE,           m_can_dirRx,     8,          10,             0,                   &CAN_3_0x39E_AC_temp_pressure_rxOverLap,           CAN_3_0x39E_AC_temp_pressure_rxBuf,           &CAN_3_0x39E_AC_temp_pressure_rxTimeout,          &CAN_3_0x39E_AC_temp_pressure_received,          NULL,                                           NULL,                                          &CAN_3_0x39E_AC_temp_pressure_rxUnpack,             &CAN_3_0x39E_AC_temp_pressure_rx_cb,          NULL                                               },/*61[AC_temp_pressure]*/
	{0x334,     m_can_norMsg,     m_can_periodMsg,     TRUE,          FALSE,           m_can_dirRx,     8,          10,            0,                   &CAN_3_0x334_BMS_alertMatrix1_rxOverLap,           CAN_3_0x334_BMS_alertMatrix1_rxBuf,           &CAN_3_0x334_BMS_alertMatrix1_rxTimeout,          &CAN_3_0x334_BMS_alertMatrix1_received,          NULL,                                           NULL,                                          &CAN_3_0x334_BMS_alertMatrix1_rxUnpack,             &CAN_3_0x334_BMS_alertMatrix1_rx_cb,          NULL                                               },/*64[BMS_alertMatrix1]*/
	{0x729,     m_can_ccpMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirRx,     8,          0,             0,                   &CCP_CAN_0x729_ccpReq_rxOverLap,                CCP_CAN_0x729_ccpReq_rxBuf,                &CCP_CAN_0x729_ccpReq_rxTimeout,               &CCP_CAN_0x729_ccpReq_received,               NULL,                                        NULL,                                       NULL,                                            NULL,                                      NULL                                            },/*82[ccpReq]*/
	{0x739,     m_can_ccpMsg,     m_can_eventMsg,      TRUE,         FALSE,           m_can_dirTx,     8,          0,             0,                   NULL,                                           CCP_CAN_0x739_ccpRsp_txBuf,                NULL,                                          NULL,                                         &CCP_CAN_0x739_ccpRsp_txReady,               &CCP_CAN_0x739_ccpRsp_txFail,               NULL,                                            NULL,                                      &CCP_CAN_0x739_ccp_txSuccessCb               },/*82[ccpRsp]*/
};


/*------------------------------------------------------------------------------
                             Local data at EEPROM
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                                Global data at ROM
------------------------------------------------------------------------------*/
const hs_u1_t canModuleNum = m_canMod_cnt;
const canMboxCfgInfo_t canMsgCfgInfoGrp[m_canMod_cnt] = 
{
    {CLASS_CANMsgCfgGrp,m_C_CAN_MsgCnt},
    {RESERVED_CANMsgCfgGrp,m_RESERVED_CAN_MsgCnt},
    {PT_CANMsgCfgGrp,m_PT_CAN_MsgCnt}
};

canMsgScheData_t * const canMsgScheCfgInfoGrp[m_canMod_cnt] = 
{
    CLASS_CANMsgScheData,RESERVED_CANMsgScheData,PT_CANMsgScheData
};


canMsgSortInfo_t * const canMsgSortInfoGrp[m_canMod_cnt] = 
{
    CLASS_CANMsgSortOrder,RESERVED_CANMsgSortOrder,PT_CANMsgSortOrder
};

uint16_t * const canTxDynMsgIndxBuf[m_canMod_cnt] =
{
	NULL,NULL,NULL
};

const uint16_t m_udsRx_phyId =	0x731;
const uint16_t m_udsRx_funId =	0x7DF;
const uint16_t m_udsTx_id	 =	0x7B1;

const hs_u1_t udsRxCanBus = m_can_udsRxBus;
const hs_u1_t udsTxCanBus = m_can_udsTxBus;
const hs_u1_t ccpRxCanBus = m_can_ccpRxBus;
const hs_u1_t ccpTxCanBus = m_can_ccpTxBus;
const hs_u2_t udsRxMsgIndx = m_can_udsRxMsgIndx;
const hs_u2_t udsTxMsgIndx = m_can_udsTxMsgIndx;
const hs_u2_t ccpRxMsgIndx = m_can_ccpRxMsgIndx;
const hs_u2_t ccpTxMsgIndx = m_can_ccpTxMsgIndx;
const hs_u1_t canBaudCfg[m_canMod_cnt] = {m_canBaud_500kps,m_canBaud_500kps,m_canBaud_500kps};

const hs_u2_t nmTxMsgIndx = 38;
/*------------------------------------------------------------------------------
                             Global data at EEPROM
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                      Implementation of global functions
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      Implementation of local functions
------------------------------------------------------------------------------*/


/* ---- Source switch off ---------------------------------------------------- */

/*--- End of file ------------------------------------------------------------*/

