/*
* Copyright (c) File,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:dtcInfo.h
* Description: This is a readonly file generated by HSNE tools and can't be modified manually. 
* REQ IDs: 
* History:
* 2017-11-07 08:41:23
*/

/* ---- Source switch on ------------------------------------------------------*/
#ifndef DTC_INFO_H_
#define DTC_INFO_H_

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "hs_types.h"
#include "didCfg_export.h"
#include "didcfg_var.h"
/*------------------------------------------------------------------------------
                             Defines and constants
------------------------------------------------------------------------------*/
#define m_dtcPrio_none 0
#define m_dtcPrio_low 1
#define m_dtcPrio_middle 2
#define m_dtcPrio_high 3


#define m_dtcInfoCnt	149
               
/*------------------------------------------------------------------------------
                                   Data types
------------------------------------------------------------------------------*/
typedef union
{
    hs_u1_t all;
    struct
    {
        hs_u1_t warnIndi:1; /*the warning indicator*/
        hs_u1_t testNotCompleteThisOperationCycle:1; /*test not completed this operation cycle*/
        hs_u1_t testFailedSinceLastClear:1; /*test failed since last clear, Latch until manually clear requested*/
        hs_u1_t testNotCompleteSinceLastClear:1; /*test not complete since last clear,  Latch until manually clear requested*/
        hs_u1_t confirmDtc:1; /*confirmed DTC,  Latch until manually clear requested or successive 40(it is up to the DTC configuration) cycles not failed(only for the dtc whose ageLimit not equal to 0xFF)*/
        hs_u1_t pendingDtc:1; /*pendingDtc*/
        hs_u1_t testFailedThisOperationCycle:1; /*test failed this operation cycle*/
        hs_u1_t testFailed:1; /*test failed*/
    }b;
}dtcStatus_t;

typedef struct
{
    hs_u1_t faultCnt;
    hs_u1_t ageCnt;
    hs_u1_t dcCnt;
    hs_BOOL isStored;
    dtcStatus_t dtcStatus;
}obdDiagDt_t;

typedef struct
{
    hs_u2_t fault_i;
    hs_u1_t ffPrio;
}obdFFDt_t;

typedef struct
{
    hs_u4_t dtcCode;
    hs_BOOL * p_flt;
    hs_BOOL * p_ok;
    hs_u1_t fltDec;
    hs_u1_t fltInc;
    hs_u1_t fltLimit;
    hs_u1_t ageLimit;
    hs_u1_t clearWarnCycle;
    hs_u1_t dcLimit;
    hs_u1_t prio;
    hs_u1_t snapDidNum;
    const hs_u2_t * pDidIndx;
    hs_u2_t snapSize;
    hs_u1_t * snapBuf;
}dtcInfoCfg_t;

typedef struct
{
    hs_u1_t dtcsnapBuf[UDS_SNAP_TOTAL_LNG];
}dtcSnapShot_t;



/*------------------------------------------------------------------------------
                      External declaration of global RAM-Variables
------------------------------------------------------------------------------*/
extern hs_u1_t __attribute__ ((section(".eeDiagDtAddr"))) vcu_TowModeSetStor;
extern hs_u1_t __attribute__ ((section(".eeDiagDtAddr"))) did_vin[17];
extern hs_u1_t __attribute__ ((section(".eeDiagDtAddr"))) DFHS_EOLDtID[DIDCFG_EOL_DTID_LNG];
extern float __attribute__ ((section(".eeDiagDtAddr"))) Inital_electri_consumption;
extern hs_u1_t __attribute__ ((section(".eeDiagDtAddr"))) uds_saInvalidAccessCnt;
extern float __attribute__ ((section(".eeDiagDtAddr"))) Cousum_RW[11];
extern obdDiagDt_t __attribute__ ((section(".eeDiagDtAddr"))) obdDiagDtGrp[m_dtcInfoCnt];
extern hs_u2_t __attribute__ ((section(".eeDiagDtAddr"))) obdFFOrder[m_dtcInfoCnt];
extern obdFFDt_t __attribute__ ((section(".eeDiagDtAddr"))) obdFFDtGrp[m_dtcInfoCnt];
/*------------------------------------------------------------------------------
                      External declaration of global ROM-Variables
------------------------------------------------------------------------------*/
extern const hs_u2_t dtcItemCnt;
extern const hs_u2_t dtcFreezeFrameCnt;
extern const dtcInfoCfg_t dtcInfoCfgGrp[m_dtcInfoCnt];




/*------------------------------------------------------------------------------
                    External declaration of global EEPROM-Variables
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                              Declaration of global functions
------------------------------------------------------------------------------*/
extern void dtcInfo_Init(void);

#endif

