/*
* Copyright (c) File,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:didCfg_var.h
* Description: This is a readonly file generated by HSNE tools and can't be modified manually. 
* REQ IDs: 
* History:
* 2017-11-01 06:50:52
*/

/* ---- Source switch on ------------------------------------------------------*/
#ifndef DID_CFG_VAR_H_
#define DID_CFG_VAR_H_

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "hs_types.h"


/*------------------------------------------------------------------------------
                             Defines and constants
------------------------------------------------------------------------------*/



               
/*------------------------------------------------------------------------------
                                   Data types
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      External declaration of global RAM-Variables
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      External declaration of global ROM-Variables
------------------------------------------------------------------------------*/
//did read
#define DIDCFG_SOFT_VAR_LNG		13
#define DIDCFG_PORT_NUM_LNG		13
#define DIDCFG_HARD_VAR_LNG		13

#define DIDCFG_SUPPLIER_NAME_LNG		10
#define DIDCFG_ECU_NAME_LNG		10
#define DIDCFG_SUPR_HARD_VAR_LNG		8
#define DIDCFG_SUPR_SOFT_VAR_LNG		21

#define DIDCFG_BOOTLOADER_VAR_LNG		16
#define DIDCFG_EOL_DTID_LNG		8

//did write
#define DIDCFG_VIN_LNG		17

extern const unsigned char DF_softwareVar[DIDCFG_SOFT_VAR_LNG];//
extern const unsigned char port_numbers[DIDCFG_PORT_NUM_LNG];//
extern const unsigned char DF_hardwareVar[DIDCFG_HARD_VAR_LNG];//
extern const unsigned char DFHS_supplierName[DIDCFG_SUPPLIER_NAME_LNG];//
extern const unsigned char DFHS_ECUName[DIDCFG_ECU_NAME_LNG];//
extern const unsigned char DFHS_supplierHardVar[DIDCFG_SUPR_HARD_VAR_LNG];//
extern const unsigned char DFHS_supplierSoftVar[DIDCFG_SUPR_SOFT_VAR_LNG];//
extern const unsigned char DFHS_BootLoaderVar[DIDCFG_BOOTLOADER_VAR_LNG];//
extern const unsigned char DFHS_EOLDtID[DIDCFG_EOL_DTID_LNG];





/*------------------------------------------------------------------------------
                    External declaration of global EEPROM-Variables
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                              Declaration of global functions
------------------------------------------------------------------------------*/


#endif

