/*
* Copyright (c) File ,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:didCfg.c
* Description: This is a readonly file generated by HSNE tools and you should implement the call-back interfaces manually.It includes UDS did information,including both Reading-Did and writing-did. 
* REQ IDs: 
* History:
* 2017-11-01 06:50:52
*/

/* ---- Source switch on ------------------------------------------------------*/

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "importTypes.h"
#include "globalVarExport.h"
#include "hs_types.h"
#include "didCfg_Var.h"
#include "didCfg_import.h"
#include "didCfg_export.h"

/*-----------------------------------------------------------------------------
                   		Module local defines and constants
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                                 Module local types
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
                                Local data at RAM
------------------------------------------------------------------------------*/
static hs_u1_t did_vin[17];

static hs_u1_t uds_snap_BattVolt;
static hs_u2_t uds_snap_VehiSpeed;
static hs_u2_t uds_snap_FrontMtrSpeed;
static hs_u2_t uds_snap_rearMtrSpeed;
static hs_u2_t uds_snap_HVBattVolt;
static hs_u2_t uds_snap_HVBattCurr;
static hs_u1_t uds_snap_HVPUpDownSt;
static hs_u1_t uds_snap_AcutalGear;
static hs_u1_t uds_snap_AccPedalPos;
static hs_u1_t uds_snap_BrakePedalPressSign;
static hs_u2_t uds_snap_EngTorque;
static hs_u2_t uds_snap_FrontMtrTorque;
static hs_u2_t uds_snap_RearMtrTorque;
static hs_u1_t uds_snap_FanSpeedPercentage;
static hs_u1_t uds_snap_Pump1SpeedPercentage;
static hs_u1_t uds_snap_Pump2SpeedPercentage;
static hs_u1_t uds_snap_Pump3SpeedPercentage;
static hs_u1_t uds_snap_3wayPosPercentage;
static hs_u1_t uds_snap_4wayPosPercentage;
static hs_u1_t uds_snap_HVBattSoc;
/*------------------------------------------------------------------------------
                                Global data at RAM
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                         Declaration of local functions
------------------------------------------------------------------------------*/
static void uds_0xF190_writeCb(void);

static void uds_0xCF00_readCb(void);
static void uds_0xCF01_readCb(void);
static void uds_0xCF03_readCb(void);
static void uds_0xCF04_readCb(void);
static void uds_0xCF06_readCb(void);
static void uds_0xCF07_readCb(void);
static void uds_0xCF08_readCb(void);
static void uds_0xCF09_readCb(void);
static void uds_0xCF0A_readCb(void);
static void uds_0xCF0B_readCb(void);
static void uds_0xCF0C_readCb(void);
static void uds_0xCF0D_readCb(void);
static void uds_0xCF0E_readCb(void);
static void uds_0xCF12_readCb(void);
static void uds_0xCF13_readCb(void);
static void uds_0xCF14_readCb(void);
static void uds_0xCF15_readCb(void);
static void uds_0xCF16_readCb(void);
static void uds_0xCF17_readCb(void);
static void uds_0xCF18_readCb(void);
/*------------------------------------------------------------------------------
                                Local data at ROM
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                             Local data at EEPROM
------------------------------------------------------------------------------*/

const hs_u2_t uds_didRdCnt = UDS_DID_RD_CNT;
const hs_u2_t uds_didWtCnt = UDS_DID_WR_CNT;

const hs_u2_t uds_snapCnt = UDS_SNAP_CNT;

/*------------------------------------------------------------------------------
                                Global data at ROM
------------------------------------------------------------------------------*/
const uds_didRdCfg_t uds_didRdCfgGrp[UDS_DID_RD_CNT]=
{
    {0xF189,DIDCFG_SOFT_VAR_LNG,(void *)DF_softwareVar,0x00,NULL},
    {0xF195,DIDCFG_SOFT_VAR_LNG,(void *)DF_softwareVar,0x00,NULL},
    {0xF187,DIDCFG_PORT_NUM_LNG,(void *)port_numbers,0x00,NULL},
    {0xF089,DIDCFG_HARD_VAR_LNG,(void *)&DF_hardwareVar,0x00,NULL},
    {0xF18A,DIDCFG_SUPPLIER_NAME_LNG,(void *)&DFHS_supplierName,0x00,NULL},
    {0xF197,DIDCFG_ECU_NAME_LNG,(void *)&DFHS_ECUName,0x00,NULL},
    {0xF193,DIDCFG_SUPR_HARD_VAR_LNG,(void *)&DFHS_supplierHardVar,0x00,NULL},
    {0xF195,DIDCFG_SUPR_SOFT_VAR_LNG,(void *)&DFHS_supplierSoftVar,0x00,NULL},
    {0xF180,DIDCFG_BOOTLOADER_VAR_LNG,(void *)&DFHS_BootLoaderVar,0x00,NULL},
	{0xF010,DIDCFG_EOL_DTID_LNG,(void *)&DFHS_EOLDtID,0x00,NULL},
};

const uds_didWtCfg_t uds_didWtCfgGrp[UDS_DID_WR_CNT]=
{
    {0xF190,DIDCFG_VIN_LNG,did_vin,GLOBAL_SA_LVL1,uds_0xF190_writeCb},
};

const uds_didRdCfg_t uds_snapListCfgGrp[UDS_SNAP_CNT]=
{
    {0xCF00,	1,	(void *)&uds_snap_BattVolt,	0x00,	uds_0xCF00_readCb},
    {0xCF01,	2,	(void *)&uds_snap_VehiSpeed,	0x00,	uds_0xCF01_readCb},
    {0xCF03,	2,	(void *)&uds_snap_FrontMtrSpeed,	0x00,	uds_0xCF03_readCb},
    {0xCF04,	2,	(void *)&uds_snap_rearMtrSpeed,	0x00,	uds_0xCF04_readCb},
    {0xCF06,	2,	(void *)&uds_snap_HVBattVolt,	0x00,	uds_0xCF06_readCb},
    {0xCF07,	2,	(void *)&uds_snap_HVBattCurr,	0x00,	uds_0xCF07_readCb},
    {0xCF08,	1,	(void *)&uds_snap_HVPUpDownSt,	0x00,	uds_0xCF08_readCb},
    {0xCF09,	1,	(void *)&uds_snap_AcutalGear,	0x00,	uds_0xCF09_readCb},
    {0xCF0A,	1,	(void *)&uds_snap_AccPedalPos,	0x00,	uds_0xCF0A_readCb},
    {0xCF0B,	1,	(void *)&uds_snap_BrakePedalPressSign,	0x00,	uds_0xCF0B_readCb},
    {0xCF0C,	2,	(void *)&uds_snap_EngTorque,	0x00,	uds_0xCF0C_readCb},
    {0xCF0D,	2,	(void *)&uds_snap_FrontMtrTorque,	0x00,	uds_0xCF0D_readCb},
    {0xCF0E,	2,	(void *)&uds_snap_RearMtrTorque,	0x00,	uds_0xCF0E_readCb},
    {0xCF12,	1,	(void *)&uds_snap_FanSpeedPercentage,	0x00,	uds_0xCF12_readCb},
    {0xCF13,	1,	(void *)&uds_snap_Pump1SpeedPercentage,	0x00,	uds_0xCF13_readCb},
    {0xCF14,	1,	(void *)&uds_snap_Pump2SpeedPercentage,	0x00,	uds_0xCF14_readCb},
    {0xCF15,	1,	(void *)&uds_snap_Pump3SpeedPercentage,	0x00,	uds_0xCF15_readCb},
    {0xCF16,	1,	(void *)&uds_snap_3wayPosPercentage,	0x00,	uds_0xCF16_readCb},
    {0xCF17,	1,	(void *)&uds_snap_4wayPosPercentage,	0x00,	uds_0xCF17_readCb},
    {0xCF18,	1,	(void *)&uds_snap_HVBattSoc,	0x00,	uds_0xCF18_readCb},
};

/*------------------------------------------------------------------------------
                             Global data at EEPROM
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                      Implementation of global functions
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      Implementation of local functions
------------------------------------------------------------------------------*/

static void uds_0xF190_writeCb(void)
{
    /*add you code here to realize this interface*/
	(void)MemIf_WriteEE(5,did_vin,DIDCFG_VIN_LNG,1);
}


static void uds_0xCF00_readCb(void)
{
    /*add you code here to realize this interface*/
	//uds_snap_BattVolt = ;
}

static void uds_0xCF01_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF03_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF04_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF06_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF07_readCb(void)
{
    /*add you code here to realize this interface*/

}


static void uds_0xCF08_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF09_readCb(void)
{
    /*add you code here to realize this interface*/

}

static void uds_0xCF0A_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF0B_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF0C_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF0D_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF0E_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF12_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF13_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF14_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF15_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF16_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF17_readCb(void)
{
    /*add you code here to realize this interface*/

}
static void uds_0xCF18_readCb(void)
{
    /*add you code here to realize this interface*/

}
/* ---- Source switch off ---------------------------------------------------- */

/*--- End of file ------------------------------------------------------------*/
