/*
* Copyright (c) File,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:didCfg_export.h
* Description: This is a readonly file generated by HSNE tools and can't be modified manually. 
* REQ IDs: 
* History:
* 2017-11-01 06:50:52
*/

/* ---- Source switch on ------------------------------------------------------*/
#ifndef DID_CFG_EXPORT_H_
#define DID_CFG_EXPORT_H_

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "hs_types.h"


/*------------------------------------------------------------------------------
                             Defines and constants
------------------------------------------------------------------------------*/
#define UDS_DID_RD_CNT	10
#define UDS_DID_WR_CNT	1

#define UDS_SNAP_CNT	20
#define UDS_SNAP_TOTAL_LNG	28
/*------------------------------------------------------------------------------
                                   Data types
------------------------------------------------------------------------------*/
typedef struct
{
    hs_u2_t did;
    hs_u2_t dlc;
    void * dtCache;
    hs_u4_t secLv;
    void (*cb)(void);
}uds_didRdCfg_t;


typedef struct
{
    hs_u2_t did;
    hs_u2_t dlc;
    hs_u1_t * dtCache;
    hs_u4_t secLv;
    void (*cb)(void);
}uds_didWtCfg_t;




/*------------------------------------------------------------------------------
                      External declaration of global RAM-Variables
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      External declaration of global ROM-Variables
------------------------------------------------------------------------------*/
extern const hs_u2_t uds_didRdCnt;
extern const hs_u2_t uds_didWtCnt;
extern const hs_u2_t uds_snapCnt;
extern const uds_didRdCfg_t uds_didRdCfgGrp[UDS_DID_RD_CNT];
extern const uds_didWtCfg_t uds_didWtCfgGrp[UDS_DID_WR_CNT];
extern const uds_didRdCfg_t uds_snapListCfgGrp[UDS_SNAP_CNT];



/*------------------------------------------------------------------------------
                    External declaration of global EEPROM-Variables
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                              Declaration of global functions
------------------------------------------------------------------------------*/


#endif

