/*
* Copyright (c) File,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:canCfg_signals.h
* Description: this is a readonly file to realize the signals pack and unpack header file, generated by HSNE tools and can't be modified manually.
* REQ IDs: 
* History:
* Time:2020/5/7 11:33:53
* User:lixiangping
*/

/* ---- Source switch on ------------------------------------------------------*/
#ifndef _CRC_8_H_
#define _CRC_8_H_

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                             Defines and constants
------------------------------------------------------------------------------*/
//multiple-term formulamultinomialorder:X^8 + X^4 + X^3 + X^2 + 1
#define CRC8_POLY_VALUE 0x1D
#define CRC8_INIT_VALUE	0

#define CRC8_CAL_BYTE_H_2_L	1

#define CRC8_CAL_LOOKUP_TABLE	1
/*------------------------------------------------------------------------------
                                   Data types
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                      External declaration of global RAM-Variables
------------------------------------------------------------------------------*/
extern unsigned char crc8_calBytes_checksum(unsigned char *ptr, unsigned char len);
extern void crc8_creat_table(void);
#endif

