/*
* Copyright (c) File ,SHENZHEN HANGSHENG NEW ENERGY Co.,Ltd.
* All Rights Reserved.
* Dept.: Software Department
* File:NVMBlockInfo.c
* Description: This is a readonly file generated by HSNE tools and can't be modified manually.It includes NVM block configure information. 
* REQ IDs: 
* History:
* Time:2020-03-23 19:10:39
* User:Devon
*/

/* ---- Source switch on ------------------------------------------------------*/

/*------------------------------------------------------------------------------
 					Include files
------------------------------------------------------------------------------*/
#include "typedefs.h"
#include "nvmBlockInfo.h"
#include "dtcInfo.h"

/*-----------------------------------------------------------------------------
                   		Module local defines and constants
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                                 Module local types
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
                                Local data at RAM
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                                Global data at RAM
------------------------------------------------------------------------------*/
hs_u1_t RTC_OffTimeLast[8] =
{
    0,    0,    0,    0,    0,    0,    0,    0
};
hs_BOOL nvmBlockDirty[m_nvmBlockCnt] =
{
    FALSE,FALSE,FALSE,FALSE,FALSE,
    FALSE,FALSE
};


/*------------------------------------------------------------------------------
                         Declaration of local functions
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                                Local data at ROM
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
                             Local data at EEPROM
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                                Global data at ROM
------------------------------------------------------------------------------*/
/*notice:1)Addr 7FAD~8000 used by bootloader
 * 		 2)The highest bit of ID indicates whether to do an data's ID alignment:1--don't compare;0--compare
 * */
const nvmBlockInfo_t nvmBlockInfoGrp[m_nvmBlockCnt] =
{
    /*id            eeAddr            dtLen     ramAddr                      ramAddrCpy             bkUpBlock    imdt              major             backUp*/         
    {0x00AA55AA,    0,                1024,     (hs_u4_t)0x40010400,         0x40000400,            5,           FALSE,            TRUE,             TRUE         }/*东风日产应用数据*/,
    {0x00929011,    1032,             1024,     (hs_u4_t)0x40010800,         0x40000400,            6,           TRUE,             TRUE,             TRUE         }/*UDS诊断数据，如VIN码,零件号等等*/,
    {0x00568000,    2064,             16384,    (hs_u4_t)0x40000000,         0x40000400,            0,           FALSE,            TRUE,             FALSE        }/*CCP协议标定数据*/,
    {0x00A0AB00,    18456,            512,      (hs_u4_t)0x40010C00,         0x40000400,            0,           FALSE,            TRUE,             FALSE        }/*EV322功能模块配置*/,
    {0x0052AC80,    18976,            8,        (hs_u4_t)RTC_OffTimeLast,    0x40000400,            0,           FALSE,            TRUE,             FALSE        }/*上次下电的时间*/,
    {0x00AA55AA,    18992,            1024,     (hs_u4_t)0x40010400,         0x40000400,            0,           FALSE,            FALSE,            TRUE         }/*东风日产应用数据*/,
    {0x00929011,    20024,            1024,     (hs_u4_t)0x40010800,         0x40000400,            0,           TRUE,             FALSE,            TRUE         }/*UDS诊断数据，如VIN码,零件号等等*/,
	{0x00AA5555,    21056,            1024,     (hs_u4_t)0x40011000,         0x40000400,            8,           TRUE,             TRUE,             TRUE         }/*东风日产周期存储数据*/,
	{0x00AA5555,    22088,            1024,     (hs_u4_t)0x40011000,         0x40000400,            0,           TRUE,             FALSE,            TRUE         }/*东风日产周期存储数据*/,

	{0x80BBF355,    23120,            DTCINFO_MASKBUF_DT_LEN,     (hs_u4_t)dtcMask_M.mask,          0x40000400,           10,           TRUE,             TRUE,             TRUE         }/*UDS立即存储数据*/,
	{0x80BBF355,    23228,            DTCINFO_MASKBUF_DT_LEN,     (hs_u4_t)dtcMask_M.mask,          0x40000400,            0,           TRUE,             FALSE,            TRUE         }/*UDS立即存储数据*/,
};
const hs_u1_t nvmBlockCnt = m_nvmBlockCnt;


/*------------------------------------------------------------------------------
                             Global data at EEPROM
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
                      Implementation of global functions
------------------------------------------------------------------------------*/
void anv_defDtInit(void)
{
    /*the default data intialize here, if the NVM data is not valid, the default data will be adopted*/
}

/*------------------------------------------------------------------------------
                      Implementation of local functions
------------------------------------------------------------------------------*/


/* ---- Source switch off ---------------------------------------------------- */

/*--- End of file ------------------------------------------------------------*/
